//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <b>CalculateMatrixRequest</b> is the data structure for calling the CalculateMatrix service.
 * 
 * <p>Java class for CalculateMatrixRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculateMatrixRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaInfo" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteRequestMetaInfoType" minOccurs="0"/>
 *         &lt;element name="RepresentationOptions" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteRepresentationOptionsType" minOccurs="0"/>
 *         &lt;element name="Start" type="{http://www.navteq.com/lbsp/Routing-Common/4}WaypointParameterType" maxOccurs="unbounded"/>
 *         &lt;element name="Destination" type="{http://www.navteq.com/lbsp/Routing-Common/4}WaypointParameterType" maxOccurs="unbounded"/>
 *         &lt;element name="AvoidArea" type="{http://www.navteq.com/lbsp/Common/4}GeoBoundingBoxType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AvoidLinks" maxOccurs="unbounded" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Common/4}LinkIdType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Mode" type="{http://www.navteq.com/lbsp/Routing-Common/4}RoutingModeType"/>
 *         &lt;element name="PublicTransportProfile" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportProfileType" minOccurs="0"/>
 *         &lt;element name="TruckProfile" type="{http://www.navteq.com/lbsp/Routing-Common/4}TruckProfileType" minOccurs="0"/>
 *         &lt;element name="SearchRange" type="{http://www.navteq.com/lbsp/Common/4}DistanceType" minOccurs="0"/>
 *         &lt;element name="MatrixAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}MatrixRouteAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SummaryAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}MatrixRouteSummaryAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Gen" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculateMatrixRequestType", namespace = "http://www.navteq.com/lbsp/Routing-CalculateMatrix/1", propOrder = {
    "metaInfo",
    "representationOptions",
    "starts",
    "destinations",
    "avoidAreas",
    "avoidLinks",
    "departure",
    "mode",
    "publicTransportProfile",
    "truckProfile",
    "searchRange",
    "matrixAttributes",
    "summaryAttributes",
    "gen"
})
public class CalculateMatrixRequestType {

    @XmlElement(name = "MetaInfo")
    protected RouteRequestMetaInfoType metaInfo;
    @XmlElement(name = "RepresentationOptions")
    protected RouteRepresentationOptionsType representationOptions;
    @XmlElement(name = "Start", required = true)
    protected List<WaypointParameterType> starts;
    @XmlElement(name = "Destination", required = true)
    protected List<WaypointParameterType> destinations;
    @XmlElement(name = "AvoidArea")
    protected List<GeoBoundingBoxType> avoidAreas;
    @XmlElementRef(name = "AvoidLinks", type = JAXBElement.class, required = false)
    protected List<JAXBElement<List<String>>> avoidLinks;
    @XmlElement(name = "Departure")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar departure;
    @XmlElement(name = "Mode", required = true)
    protected RoutingModeType mode;
    @XmlElement(name = "PublicTransportProfile")
    protected PublicTransportProfileType publicTransportProfile;
    @XmlElement(name = "TruckProfile")
    protected TruckProfileType truckProfile;
    @XmlElement(name = "SearchRange")
    protected Double searchRange;
    @XmlList
    @XmlElement(name = "MatrixAttributes")
    protected List<MatrixRouteAttributeType> matrixAttributes;
    @XmlList
    @XmlElement(name = "SummaryAttributes")
    protected List<MatrixRouteSummaryAttributeType> summaryAttributes;
    @XmlElement(name = "Gen")
    protected Integer gen;

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRequestMetaInfoType }
     *     
     */
    public RouteRequestMetaInfoType getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRequestMetaInfoType }
     *     
     */
    public void setMetaInfo(RouteRequestMetaInfoType value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the representationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRepresentationOptionsType }
     *     
     */
    public RouteRepresentationOptionsType getRepresentationOptions() {
        return representationOptions;
    }

    /**
     * Sets the value of the representationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRepresentationOptionsType }
     *     
     */
    public void setRepresentationOptions(RouteRepresentationOptionsType value) {
        this.representationOptions = value;
    }

    /**
     * Gets the value of the starts property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the starts property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStarts().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaypointParameterType }
     * 
     * 
     */
    public List<WaypointParameterType> getStarts() {
        if (starts == null) {
            starts = new ArrayList<WaypointParameterType>();
        }
        return this.starts;
    }

    /**
     * Gets the value of the destinations property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the destinations property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDestinations().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaypointParameterType }
     * 
     * 
     */
    public List<WaypointParameterType> getDestinations() {
        if (destinations == null) {
            destinations = new ArrayList<WaypointParameterType>();
        }
        return this.destinations;
    }

    /**
     * Gets the value of the avoidAreas property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidAreas property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidAreas().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoBoundingBoxType }
     * 
     * 
     */
    public List<GeoBoundingBoxType> getAvoidAreas() {
        if (avoidAreas == null) {
            avoidAreas = new ArrayList<GeoBoundingBoxType>();
        }
        return this.avoidAreas;
    }

    /**
     * Gets the value of the avoidLinks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidLinks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}
     * 
     * 
     */
    public List<JAXBElement<List<String>>> getAvoidLinks() {
        if (avoidLinks == null) {
            avoidLinks = new ArrayList<JAXBElement<List<String>>>();
        }
        return this.avoidLinks;
    }

    /**
     * Gets the value of the departure property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeparture() {
        return departure;
    }

    /**
     * Sets the value of the departure property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeparture(XMLGregorianCalendar value) {
        this.departure = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link RoutingModeType }
     *     
     */
    public RoutingModeType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoutingModeType }
     *     
     */
    public void setMode(RoutingModeType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the publicTransportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link PublicTransportProfileType }
     *     
     */
    public PublicTransportProfileType getPublicTransportProfile() {
        return publicTransportProfile;
    }

    /**
     * Sets the value of the publicTransportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicTransportProfileType }
     *     
     */
    public void setPublicTransportProfile(PublicTransportProfileType value) {
        this.publicTransportProfile = value;
    }

    /**
     * Gets the value of the truckProfile property.
     * 
     * @return
     *     possible object is
     *     {@link TruckProfileType }
     *     
     */
    public TruckProfileType getTruckProfile() {
        return truckProfile;
    }

    /**
     * Sets the value of the truckProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TruckProfileType }
     *     
     */
    public void setTruckProfile(TruckProfileType value) {
        this.truckProfile = value;
    }

    /**
     * Gets the value of the searchRange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSearchRange() {
        return searchRange;
    }

    /**
     * Sets the value of the searchRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSearchRange(Double value) {
        this.searchRange = value;
    }

    /**
     * Gets the value of the matrixAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the matrixAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMatrixAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MatrixRouteAttributeType }
     * 
     * 
     */
    public List<MatrixRouteAttributeType> getMatrixAttributes() {
        if (matrixAttributes == null) {
            matrixAttributes = new ArrayList<MatrixRouteAttributeType>();
        }
        return this.matrixAttributes;
    }

    /**
     * Gets the value of the summaryAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the summaryAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSummaryAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MatrixRouteSummaryAttributeType }
     * 
     * 
     */
    public List<MatrixRouteSummaryAttributeType> getSummaryAttributes() {
        if (summaryAttributes == null) {
            summaryAttributes = new ArrayList<MatrixRouteSummaryAttributeType>();
        }
        return this.summaryAttributes;
    }

    /**
     * Gets the value of the gen property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGen() {
        return gen;
    }

    /**
     * Sets the value of the gen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGen(Integer value) {
        this.gen = value;
    }

}
