//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalculateMatrixType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculateMatrixType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}CalculateMatrixRequestType" minOccurs="0"/>
 *         &lt;element name="Response" type="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}CalculateMatrixResponseType" minOccurs="0"/>
 *         &lt;element name="Status" type="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}CalculateMatrixStatusType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculateMatrixType", namespace = "http://www.navteq.com/lbsp/Routing-CalculateMatrix/1", propOrder = {
    "request",
    "response",
    "status"
})
public class CalculateMatrixType {

    @XmlElement(name = "Request")
    protected CalculateMatrixRequestType request;
    @XmlElement(name = "Response")
    protected CalculateMatrixResponseType response;
    @XmlElement(name = "Status")
    protected CalculateMatrixStatusType status;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateMatrixRequestType }
     *     
     */
    public CalculateMatrixRequestType getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateMatrixRequestType }
     *     
     */
    public void setRequest(CalculateMatrixRequestType value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateMatrixResponseType }
     *     
     */
    public CalculateMatrixResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateMatrixResponseType }
     *     
     */
    public void setResponse(CalculateMatrixResponseType value) {
        this.response = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateMatrixStatusType }
     *     
     */
    public CalculateMatrixStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateMatrixStatusType }
     *     
     */
    public void setStatus(CalculateMatrixStatusType value) {
        this.status = value;
    }

}
