//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CorridorAreaType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="CorridorAreaType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="start"/>
 *     &lt;enumeration value="destination"/>
 *     &lt;enumeration value="endpoints"/>
 *     &lt;enumeration value="waypoints"/>
 *     &lt;enumeration value="route"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "CorridorAreaType")
@XmlEnum
public enum CorridorAreaType {

    @XmlEnumValue("start")
    START("start"),
    @XmlEnumValue("destination")
    DESTINATION("destination"),
    @XmlEnumValue("endpoints")
    ENDPOINTS("endpoints"),
    @XmlEnumValue("waypoints")
    WAYPOINTS("waypoints"),
    @XmlEnumValue("route")
    ROUTE("route");
    private final String value;

    CorridorAreaType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static CorridorAreaType fromValue(String v) {
        for (CorridorAreaType c: CorridorAreaType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
