//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix;

import java.math.BigInteger;
import java.util.List;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _CalculateMatrix_QNAME = new QName("http://www.navteq.com/lbsp/Routing-CalculateMatrix/1", "CalculateMatrix");
    private final static QName _CalculateMatrixRequestTypeAvoidLinks_QNAME = new QName("", "AvoidLinks");
    private final static QName _PublicTransportRouteSummaryTypeDelayReason_QNAME = new QName("", "DelayReason");
    private final static QName _PublicTransportRouteSummaryTypeNumberOfChanges_QNAME = new QName("", "NumberOfChanges");
    private final static QName _PublicTransportRouteSummaryTypeDeparture_QNAME = new QName("", "Departure");
    private final static QName _PublicTransportRouteSummaryTypeRouteQualifier_QNAME = new QName("", "RouteQualifier");
    private final static QName _PublicTransportRouteSummaryTypeWalkTime_QNAME = new QName("", "WalkTime");
    private final static QName _PublicTransportRouteSummaryTypeTransportTypes_QNAME = new QName("", "TransportTypes");
    private final static QName _PublicTransportRouteSummaryTypeWaitTime_QNAME = new QName("", "WaitTime");
    private final static QName _PublicTransportRouteSummaryTypeTimePrognosis_QNAME = new QName("", "TimePrognosis");
    private final static QName _PublicTransportRouteSummaryTypeTravelTime_QNAME = new QName("", "TravelTime");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CalculateMatrixType }
     * 
     */
    public CalculateMatrixType createCalculateMatrixType() {
        return new CalculateMatrixType();
    }

    /**
     * Create an instance of {@link RouteMatrixEntryType }
     * 
     */
    public RouteMatrixEntryType createRouteMatrixEntryType() {
        return new RouteMatrixEntryType();
    }

    /**
     * Create an instance of {@link CalculateMatrixStatusType }
     * 
     */
    public CalculateMatrixStatusType createCalculateMatrixStatusType() {
        return new CalculateMatrixStatusType();
    }

    /**
     * Create an instance of {@link CalculateMatrixResponseType }
     * 
     */
    public CalculateMatrixResponseType createCalculateMatrixResponseType() {
        return new CalculateMatrixResponseType();
    }

    /**
     * Create an instance of {@link CalculateMatrixRequestType }
     * 
     */
    public CalculateMatrixRequestType createCalculateMatrixRequestType() {
        return new CalculateMatrixRequestType();
    }

    /**
     * Create an instance of {@link GeoPositionType }
     * 
     */
    public GeoPositionType createGeoPositionType() {
        return new GeoPositionType();
    }

    /**
     * Create an instance of {@link GeoCorridorType }
     * 
     */
    public GeoCorridorType createGeoCorridorType() {
        return new GeoCorridorType();
    }

    /**
     * Create an instance of {@link StreetType }
     * 
     */
    public StreetType createStreetType() {
        return new StreetType();
    }

    /**
     * Create an instance of {@link PeriodType }
     * 
     */
    public PeriodType createPeriodType() {
        return new PeriodType();
    }

    /**
     * Create an instance of {@link GeoProximityType }
     * 
     */
    public GeoProximityType createGeoProximityType() {
        return new GeoProximityType();
    }

    /**
     * Create an instance of {@link GeoBoundingBoxType }
     * 
     */
    public GeoBoundingBoxType createGeoBoundingBoxType() {
        return new GeoBoundingBoxType();
    }

    /**
     * Create an instance of {@link UserContextType }
     * 
     */
    public UserContextType createUserContextType() {
        return new UserContextType();
    }

    /**
     * Create an instance of {@link KeyValuePairType }
     * 
     */
    public KeyValuePairType createKeyValuePairType() {
        return new KeyValuePairType();
    }

    /**
     * Create an instance of {@link GeoCoordinateType }
     * 
     */
    public GeoCoordinateType createGeoCoordinateType() {
        return new GeoCoordinateType();
    }

    /**
     * Create an instance of {@link LocalizedNameType }
     * 
     */
    public LocalizedNameType createLocalizedNameType() {
        return new LocalizedNameType();
    }

    /**
     * Create an instance of {@link WKTShapeType }
     * 
     */
    public WKTShapeType createWKTShapeType() {
        return new WKTShapeType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AlternativeValueType }
     * 
     */
    public AlternativeValueType createAlternativeValueType() {
        return new AlternativeValueType();
    }

    /**
     * Create an instance of {@link RouteResponseMetaInfoType }
     * 
     */
    public RouteResponseMetaInfoType createRouteResponseMetaInfoType() {
        return new RouteResponseMetaInfoType();
    }

    /**
     * Create an instance of {@link PublicTransportProfileType }
     * 
     */
    public PublicTransportProfileType createPublicTransportProfileType() {
        return new PublicTransportProfileType();
    }

    /**
     * Create an instance of {@link SourceSupplierType }
     * 
     */
    public SourceSupplierType createSourceSupplierType() {
        return new SourceSupplierType();
    }

    /**
     * Create an instance of {@link NavigationWaypointParameterType }
     * 
     */
    public NavigationWaypointParameterType createNavigationWaypointParameterType() {
        return new NavigationWaypointParameterType();
    }

    /**
     * Create an instance of {@link PublicTransportLinkType }
     * 
     */
    public PublicTransportLinkType createPublicTransportLinkType() {
        return new PublicTransportLinkType();
    }

    /**
     * Create an instance of {@link GeoWaypointParameterType }
     * 
     */
    public GeoWaypointParameterType createGeoWaypointParameterType() {
        return new GeoWaypointParameterType();
    }

    /**
     * Create an instance of {@link PrivateTransportManeuverType }
     * 
     */
    public PrivateTransportManeuverType createPrivateTransportManeuverType() {
        return new PrivateTransportManeuverType();
    }

    /**
     * Create an instance of {@link PublicTransportRouteSummaryType }
     * 
     */
    public PublicTransportRouteSummaryType createPublicTransportRouteSummaryType() {
        return new PublicTransportRouteSummaryType();
    }

    /**
     * Create an instance of {@link PrivateTransportLinkType }
     * 
     */
    public PrivateTransportLinkType createPrivateTransportLinkType() {
        return new PrivateTransportLinkType();
    }

    /**
     * Create an instance of {@link RouteSummaryEntryType }
     * 
     */
    public RouteSummaryEntryType createRouteSummaryEntryType() {
        return new RouteSummaryEntryType();
    }

    /**
     * Create an instance of {@link GeoPositionLogType }
     * 
     */
    public GeoPositionLogType createGeoPositionLogType() {
        return new GeoPositionLogType();
    }

    /**
     * Create an instance of {@link ExternalResourceType }
     * 
     */
    public ExternalResourceType createExternalResourceType() {
        return new ExternalResourceType();
    }

    /**
     * Create an instance of {@link IncidentType }
     * 
     */
    public IncidentType createIncidentType() {
        return new IncidentType();
    }

    /**
     * Create an instance of {@link RouteSummaryType }
     * 
     */
    public RouteSummaryType createRouteSummaryType() {
        return new RouteSummaryType();
    }

    /**
     * Create an instance of {@link IntersectionLegType }
     * 
     */
    public IntersectionLegType createIntersectionLegType() {
        return new IntersectionLegType();
    }

    /**
     * Create an instance of {@link RouteRepresentationOptionsType }
     * 
     */
    public RouteRepresentationOptionsType createRouteRepresentationOptionsType() {
        return new RouteRepresentationOptionsType();
    }

    /**
     * Create an instance of {@link WeightedRouteFeatureType }
     * 
     */
    public WeightedRouteFeatureType createWeightedRouteFeatureType() {
        return new WeightedRouteFeatureType();
    }

    /**
     * Create an instance of {@link ManeuverGroupType }
     * 
     */
    public ManeuverGroupType createManeuverGroupType() {
        return new ManeuverGroupType();
    }

    /**
     * Create an instance of {@link IntersectionIconType }
     * 
     */
    public IntersectionIconType createIntersectionIconType() {
        return new IntersectionIconType();
    }

    /**
     * Create an instance of {@link RouteNoteType }
     * 
     */
    public RouteNoteType createRouteNoteType() {
        return new RouteNoteType();
    }

    /**
     * Create an instance of {@link SourceAttributionType }
     * 
     */
    public SourceAttributionType createSourceAttributionType() {
        return new SourceAttributionType();
    }

    /**
     * Create an instance of {@link RoutingModeType }
     * 
     */
    public RoutingModeType createRoutingModeType() {
        return new RoutingModeType();
    }

    /**
     * Create an instance of {@link DynamicSpeedInfoType }
     * 
     */
    public DynamicSpeedInfoType createDynamicSpeedInfoType() {
        return new DynamicSpeedInfoType();
    }

    /**
     * Create an instance of {@link GeneralizationType }
     * 
     */
    public GeneralizationType createGeneralizationType() {
        return new GeneralizationType();
    }

    /**
     * Create an instance of {@link CorridorToleranceLevelType }
     * 
     */
    public CorridorToleranceLevelType createCorridorToleranceLevelType() {
        return new CorridorToleranceLevelType();
    }

    /**
     * Create an instance of {@link CorridorRepresentationOptionsType }
     * 
     */
    public CorridorRepresentationOptionsType createCorridorRepresentationOptionsType() {
        return new CorridorRepresentationOptionsType();
    }

    /**
     * Create an instance of {@link RouteLaneType }
     * 
     */
    public RouteLaneType createRouteLaneType() {
        return new RouteLaneType();
    }

    /**
     * Create an instance of {@link VehicleType }
     * 
     */
    public VehicleType createVehicleType() {
        return new VehicleType();
    }

    /**
     * Create an instance of {@link RouteType }
     * 
     */
    public RouteType createRouteType() {
        return new RouteType();
    }

    /**
     * Create an instance of {@link PublicTransportLineType }
     * 
     */
    public PublicTransportLineType createPublicTransportLineType() {
        return new PublicTransportLineType();
    }

    /**
     * Create an instance of {@link LinkPositionType }
     * 
     */
    public LinkPositionType createLinkPositionType() {
        return new LinkPositionType();
    }

    /**
     * Create an instance of {@link WaypointType }
     * 
     */
    public WaypointType createWaypointType() {
        return new WaypointType();
    }

    /**
     * Create an instance of {@link RouteLegType }
     * 
     */
    public RouteLegType createRouteLegType() {
        return new RouteLegType();
    }

    /**
     * Create an instance of {@link TruckProfileType }
     * 
     */
    public TruckProfileType createTruckProfileType() {
        return new TruckProfileType();
    }

    /**
     * Create an instance of {@link PositioningWaypointParameterType }
     * 
     */
    public PositioningWaypointParameterType createPositioningWaypointParameterType() {
        return new PositioningWaypointParameterType();
    }

    /**
     * Create an instance of {@link PublicTransportManeuverType }
     * 
     */
    public PublicTransportManeuverType createPublicTransportManeuverType() {
        return new PublicTransportManeuverType();
    }

    /**
     * Create an instance of {@link PublicTransportWaypointParameterType }
     * 
     */
    public PublicTransportWaypointParameterType createPublicTransportWaypointParameterType() {
        return new PublicTransportWaypointParameterType();
    }

    /**
     * Create an instance of {@link RouteRequestMetaInfoType }
     * 
     */
    public RouteRequestMetaInfoType createRouteRequestMetaInfoType() {
        return new RouteRequestMetaInfoType();
    }

    /**
     * Create an instance of {@link PublicTransportStopType }
     * 
     */
    public PublicTransportStopType createPublicTransportStopType() {
        return new PublicTransportStopType();
    }

    /**
     * Create an instance of {@link RouteSummaryByCountryType }
     * 
     */
    public RouteSummaryByCountryType createRouteSummaryByCountryType() {
        return new RouteSummaryByCountryType();
    }

    /**
     * Create an instance of {@link TruckRestrictionsType }
     * 
     */
    public TruckRestrictionsType createTruckRestrictionsType() {
        return new TruckRestrictionsType();
    }

    /**
     * Create an instance of {@link TravelProgressType }
     * 
     */
    public TravelProgressType createTravelProgressType() {
        return new TravelProgressType();
    }

    /**
     * Create an instance of {@link SourceSupplierNoteType }
     * 
     */
    public SourceSupplierNoteType createSourceSupplierNoteType() {
        return new SourceSupplierNoteType();
    }

    /**
     * Create an instance of {@link StreetPositionType }
     * 
     */
    public StreetPositionType createStreetPositionType() {
        return new StreetPositionType();
    }

    /**
     * Create an instance of {@link RoadShieldType }
     * 
     */
    public RoadShieldType createRoadShieldType() {
        return new RoadShieldType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link CalculateMatrixType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navteq.com/lbsp/Routing-CalculateMatrix/1", name = "CalculateMatrix")
    public JAXBElement<CalculateMatrixType> createCalculateMatrix(CalculateMatrixType value) {
        return new JAXBElement<CalculateMatrixType>(_CalculateMatrix_QNAME, CalculateMatrixType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link String }{@code >}{@code >}}
     * 
     */
    @SuppressWarnings({ "unchecked", "rawtypes" })
	@XmlElementDecl(namespace = "", name = "AvoidLinks", scope = CalculateMatrixRequestType.class)
    public JAXBElement<List<String>> createCalculateMatrixRequestTypeAvoidLinks(List<String> value) {
        return new JAXBElement<List<String>>(_CalculateMatrixRequestTypeAvoidLinks_QNAME, ((Class) List.class), CalculateMatrixRequestType.class, ((List<String> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DelayReason", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<String> createPublicTransportRouteSummaryTypeDelayReason(String value) {
        return new JAXBElement<String>(_PublicTransportRouteSummaryTypeDelayReason_QNAME, String.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumberOfChanges", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<BigInteger> createPublicTransportRouteSummaryTypeNumberOfChanges(BigInteger value) {
        return new JAXBElement<BigInteger>(_PublicTransportRouteSummaryTypeNumberOfChanges_QNAME, BigInteger.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Departure", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<XMLGregorianCalendar> createPublicTransportRouteSummaryTypeDeparture(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_PublicTransportRouteSummaryTypeDeparture_QNAME, XMLGregorianCalendar.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link RouteQualifierType }{@code >}{@code >}}
     * 
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
	@XmlElementDecl(namespace = "", name = "RouteQualifier", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<List<RouteQualifierType>> createPublicTransportRouteSummaryTypeRouteQualifier(List<RouteQualifierType> value) {
        return new JAXBElement<List<RouteQualifierType>>(_PublicTransportRouteSummaryTypeRouteQualifier_QNAME, ((Class) List.class), PublicTransportRouteSummaryType.class, ((List<RouteQualifierType> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WalkTime", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<Double> createPublicTransportRouteSummaryTypeWalkTime(Double value) {
        return new JAXBElement<Double>(_PublicTransportRouteSummaryTypeWalkTime_QNAME, Double.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code <}{@link PublicTransportTypeType }{@code >}{@code >}}
     * 
     */
    @SuppressWarnings({ "rawtypes", "unchecked" })
	@XmlElementDecl(namespace = "", name = "TransportTypes", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<List<PublicTransportTypeType>> createPublicTransportRouteSummaryTypeTransportTypes(List<PublicTransportTypeType> value) {
        return new JAXBElement<List<PublicTransportTypeType>>(_PublicTransportRouteSummaryTypeTransportTypes_QNAME, ((Class) List.class), PublicTransportRouteSummaryType.class, ((List<PublicTransportTypeType> ) value));
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "WaitTime", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<Double> createPublicTransportRouteSummaryTypeWaitTime(Double value) {
        return new JAXBElement<Double>(_PublicTransportRouteSummaryTypeWaitTime_QNAME, Double.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TimePrognosis", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<String> createPublicTransportRouteSummaryTypeTimePrognosis(String value) {
        return new JAXBElement<String>(_PublicTransportRouteSummaryTypeTimePrognosis_QNAME, String.class, PublicTransportRouteSummaryType.class, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Double }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TravelTime", scope = PublicTransportRouteSummaryType.class)
    public JAXBElement<Double> createPublicTransportRouteSummaryTypeTravelTime(Double value) {
        return new JAXBElement<Double>(_PublicTransportRouteSummaryTypeTravelTime_QNAME, Double.class, PublicTransportRouteSummaryType.class, value);
    }

}
