//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculatematrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Instances of PublicTransportStopType Represent stops on a public transport line. Stops are different from stations as they are bound to a specific public transport line and a direction of travel, indicated by the line's destination.
 * 
 * <p>Java class for PublicTransportStopType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicTransportStopType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Position" type="{http://www.navteq.com/lbsp/Common/4}GeoCoordinateType"/>
 *         &lt;element name="Line" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="StopName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="StopId" type="{http://www.navteq.com/lbsp/Common/4}TransitStopIdType" minOccurs="0"/>
 *         &lt;element name="NextStopId" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="TravelTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id3" use="required" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicTransportStopType", propOrder = {
    "position",
    "line",
    "stopName",
    "stopId",
    "nextStopId",
    "travelTime"
})
public class PublicTransportStopType {

    @XmlElement(name = "Position", required = true)
    protected GeoCoordinateType position;
    @XmlElement(name = "Line")
    protected String line;
    @XmlElement(name = "StopName")
    protected String stopName;
    @XmlElement(name = "StopId")
    protected String stopId;
    @XmlElement(name = "NextStopId")
    protected String nextStopId;
    @XmlElement(name = "TravelTime")
    protected Double travelTime;
    @XmlAttribute(name = "id3", required = true)
    protected String id3;

    /**
     * Gets the value of the position property.
     * 
     * @return
     *     possible object is
     *     {@link GeoCoordinateType }
     *     
     */
    public GeoCoordinateType getPosition() {
        return position;
    }

    /**
     * Sets the value of the position property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoCoordinateType }
     *     
     */
    public void setPosition(GeoCoordinateType value) {
        this.position = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the stopName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopName() {
        return stopName;
    }

    /**
     * Sets the value of the stopName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopName(String value) {
        this.stopName = value;
    }

    /**
     * Gets the value of the stopId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopId() {
        return stopId;
    }

    /**
     * Sets the value of the stopId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopId(String value) {
        this.stopId = value;
    }

    /**
     * Gets the value of the nextStopId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextStopId() {
        return nextStopId;
    }

    /**
     * Sets the value of the nextStopId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextStopId(String value) {
        this.nextStopId = value;
    }

    /**
     * Gets the value of the travelTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTravelTime() {
        return travelTime;
    }

    /**
     * Sets the value of the travelTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTravelTime(Double value) {
        this.travelTime = value;
    }

    /**
     * Gets the value of the id3 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId3() {
        return id3;
    }

    /**
     * Sets the value of the id3 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId3(String value) {
        this.id3 = value;
    }

}
