//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * A group of maneuvers using the same transport type. This type is especially useful for multi modal routes.
 * 
 * <p>Java class for ManeuverGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ManeuverGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="FirstManeuver" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="LastManeuver" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="Mode" type="{http://www.navteq.com/lbsp/Routing-Common/4}TransportModeType" minOccurs="0"/>
 *         &lt;element name="PublicTransportType" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportTypeType" minOccurs="0"/>
 *         &lt;element name="SummaryDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="ArrivalDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WaitDescription" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Summary" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteSummaryType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ManeuverGroupType", propOrder = {
    "firstManeuver",
    "lastManeuver",
    "mode",
    "publicTransportType",
    "summaryDescription",
    "arrivalDescription",
    "waitDescription",
    "summary"
})
public class ManeuverGroupType {

    @XmlElement(name = "FirstManeuver")
    protected String firstManeuver;
    @XmlElement(name = "LastManeuver")
    protected String lastManeuver;
    @XmlElement(name = "Mode")
    protected TransportModeType mode;
    @XmlElement(name = "PublicTransportType")
    protected PublicTransportTypeType publicTransportType;
    @XmlElement(name = "SummaryDescription")
    protected String summaryDescription;
    @XmlElement(name = "ArrivalDescription")
    protected String arrivalDescription;
    @XmlElement(name = "WaitDescription")
    protected String waitDescription;
    @XmlElement(name = "Summary")
    protected RouteSummaryType summary;

    /**
     * Gets the value of the firstManeuver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstManeuver() {
        return firstManeuver;
    }

    /**
     * Sets the value of the firstManeuver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstManeuver(String value) {
        this.firstManeuver = value;
    }

    /**
     * Gets the value of the lastManeuver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastManeuver() {
        return lastManeuver;
    }

    /**
     * Sets the value of the lastManeuver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastManeuver(String value) {
        this.lastManeuver = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * @return
     *     possible object is
     *     {@link TransportModeType }
     *     
     */
    public TransportModeType getMode() {
        return mode;
    }

    /**
     * Sets the value of the mode property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransportModeType }
     *     
     */
    public void setMode(TransportModeType value) {
        this.mode = value;
    }

    /**
     * Gets the value of the publicTransportType property.
     * 
     * @return
     *     possible object is
     *     {@link PublicTransportTypeType }
     *     
     */
    public PublicTransportTypeType getPublicTransportType() {
        return publicTransportType;
    }

    /**
     * Sets the value of the publicTransportType property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicTransportTypeType }
     *     
     */
    public void setPublicTransportType(PublicTransportTypeType value) {
        this.publicTransportType = value;
    }

    /**
     * Gets the value of the summaryDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSummaryDescription() {
        return summaryDescription;
    }

    /**
     * Sets the value of the summaryDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSummaryDescription(String value) {
        this.summaryDescription = value;
    }

    /**
     * Gets the value of the arrivalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrivalDescription() {
        return arrivalDescription;
    }

    /**
     * Sets the value of the arrivalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrivalDescription(String value) {
        this.arrivalDescription = value;
    }

    /**
     * Gets the value of the waitDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWaitDescription() {
        return waitDescription;
    }

    /**
     * Sets the value of the waitDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWaitDescription(String value) {
        this.waitDescription = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link RouteSummaryType }
     *     
     */
    public RouteSummaryType getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteSummaryType }
     *     
     */
    public void setSummary(RouteSummaryType value) {
        this.summary = value;
    }

}
