//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ManeuverAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ManeuverAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="position"/>
 *     &lt;enumeration value="shape"/>
 *     &lt;enumeration value="travelTime"/>
 *     &lt;enumeration value="length"/>
 *     &lt;enumeration value="time"/>
 *     &lt;enumeration value="link"/>
 *     &lt;enumeration value="publicTransportLine"/>
 *     &lt;enumeration value="platform"/>
 *     &lt;enumeration value="equipment"/>
 *     &lt;enumeration value="lane"/>
 *     &lt;enumeration value="roadName"/>
 *     &lt;enumeration value="nextRoadName"/>
 *     &lt;enumeration value="roadNumber"/>
 *     &lt;enumeration value="nextRoadNumber"/>
 *     &lt;enumeration value="roadTemplate"/>
 *     &lt;enumeration value="signPost"/>
 *     &lt;enumeration value="notes"/>
 *     &lt;enumeration value="action"/>
 *     &lt;enumeration value="direction"/>
 *     &lt;enumeration value="nextManeuver"/>
 *     &lt;enumeration value="freewayExit"/>
 *     &lt;enumeration value="freewayJunction"/>
 *     &lt;enumeration value="baseTime"/>
 *     &lt;enumeration value="trafficTime"/>
 *     &lt;enumeration value="indices"/>
 *     &lt;enumeration value="boundingBox"/>
 *     &lt;enumeration value="compressedShapes"/>
 *     &lt;enumeration value="roadShield"/>
 *     &lt;enumeration value="startAngle"/>
 *     &lt;enumeration value="waitTime"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ManeuverAttributeType")
@XmlEnum
public enum ManeuverAttributeType {


    /**
     * Short value: "po". Indicates whether the position should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("position")
    POSITION("position"),

    /**
     * Short value: "sh". Indicates whether the shape of the segment to the next maneuver should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("shape")
    SHAPE("shape"),

    /**
     * Short value: "tt". Indicates whether the time needed to the next maneuver should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("travelTime")
    TRAVEL_TIME("travelTime"),

    /**
     * Short value: "le". Indicates whether the distance to the next maneuver should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("length")
    LENGTH("length"),

    /**
     * Short value: "ti". Indicates whether the point in time when the maneuver will take place should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("time")
    TIME("time"),

    /**
     * Short value: "li". Indicates whether the link where the maneuver takes place shall be included in the maneuver.
     * 
     */
    @XmlEnumValue("link")
    LINK("link"),

    /**
     * Short value: "pt". Indicates whether the information about the public transport line should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("publicTransportLine")
    PUBLIC_TRANSPORT_LINE("publicTransportLine"),

    /**
     * Short value: "pl". Indicates whether the platform information for a public transport line should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("platform")
    PLATFORM("platform"),

    /**
     * Short value: "eq". Indicates whether equipment at the maneuver should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("equipment")
    EQUIPMENT("equipment"),

    /**
     * Short value: "la". Indicates whether lane information should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("lane")
    LANE("lane"),

    /**
     * Short value: "rn". Indicates whether the road name should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("roadName")
    ROAD_NAME("roadName"),

    /**
     * Short value: "nr". Indicates whether the name of the next road shall be included in the maneuvers.
     * 
     */
    @XmlEnumValue("nextRoadName")
    NEXT_ROAD_NAME("nextRoadName"),

    /**
     * Short value: "ru". Indicates whether the road number should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("roadNumber")
    ROAD_NUMBER("roadNumber"),

    /**
     * Short value: "nu". Indicates whether the number of the next road should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("nextRoadNumber")
    NEXT_ROAD_NUMBER("nextRoadNumber"),

    /**
     * Short value: "rt". Indicates whether the template for route display should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("roadTemplate")
    ROAD_TEMPLATE("roadTemplate"),

    /**
     * Short value: "sp". Indicates whether the sign post information should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("signPost")
    SIGN_POST("signPost"),

    /**
     * Short value: "no". Indicates whether additional notes should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("notes")
    NOTES("notes"),

    /**
     * Short value: "ac". Indicates whether actions should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("action")
    ACTION("action"),

    /**
     * Short value: "di". Indicates whether directions should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("direction")
    DIRECTION("direction"),

    /**
     * Short value: "nm". Indicates whether a reference to the next maneuver should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("nextManeuver")
    NEXT_MANEUVER("nextManeuver"),

    /**
     * Short value: "fe". Indicates whether the freeway exit should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("freewayExit")
    FREEWAY_EXIT("freewayExit"),

    /**
     * Short value: "fj". Indicates whether the freeway junction should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("freewayJunction")
    FREEWAY_JUNCTION("freewayJunction"),

    /**
     * Short value: "bt": Indicates whether the BaseTime information should be included in the maneuvers. By default, BaseTime information is not included in the maneuvers.
     * 
     */
    @XmlEnumValue("baseTime")
    BASE_TIME("baseTime"),

    /**
     * Short value: "tm": Indicates whether the TrafficTime information should be included in the maneuvers. By default, TrafficTime information is not included in the maneuvers.
     * 
     */
    @XmlEnumValue("trafficTime")
    TRAFFIC_TIME("trafficTime"),

    /**
     * Short value: "ix": Indicates whether shape index information (FirstPoint, LastPoint) should be included in the maneuvers instead of copying shape points to the maneuver.
     * 
     */
    @XmlEnumValue("indices")
    INDICES("indices"),

    /**
     * Short value: "bb". Indicates whether the bounding box of the maneuver shall be provided.
     * 
     */
    @XmlEnumValue("boundingBox")
    BOUNDING_BOX("boundingBox"),

    /**
     * Short value: "sz": Indicates whether compressed shape information should be included in the maneuvers. Shape compression may considerably reduce the amount of data transferred.
     * 
     */
    @XmlEnumValue("compressedShapes")
    COMPRESSED_SHAPES("compressedShapes"),

    /**
     * Short value: "rs": Indicates whether road shield information should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("roadShield")
    ROAD_SHIELD("roadShield"),

    /**
     * Short value: "sa": Indicates whether the start angle should be included in the maneuvers.
     * 
     */
    @XmlEnumValue("startAngle")
    START_ANGLE("startAngle"),

    /**
     * Short value: "wt": Indicates whether wait time information should be included in public transport maneuvers.
     * 
     */
    @XmlEnumValue("waitTime")
    WAIT_TIME("waitTime");
    private final String value;

    ManeuverAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ManeuverAttributeType fromValue(String v) {
        for (ManeuverAttributeType c: ManeuverAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
