//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PlaceEquipmentType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="PlaceEquipmentType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stairs"/>
 *     &lt;enumeration value="elevator"/>
 *     &lt;enumeration value="escalator"/>
 *     &lt;enumeration value="barrierFree"/>
 *     &lt;enumeration value="shelter"/>
 *     &lt;enumeration value="restroom"/>
 *     &lt;enumeration value="shopping"/>
 *     &lt;enumeration value="restaurant"/>
 *     &lt;enumeration value="baggageRoom"/>
 *     &lt;enumeration value="bikeDepot"/>
 *     &lt;enumeration value="bikeAccepted"/>
 *     &lt;enumeration value="parking"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "PlaceEquipmentType")
@XmlEnum
public enum PlaceEquipmentType {

    @XmlEnumValue("stairs")
    STAIRS("stairs"),
    @XmlEnumValue("elevator")
    ELEVATOR("elevator"),
    @XmlEnumValue("escalator")
    ESCALATOR("escalator"),
    @XmlEnumValue("barrierFree")
    BARRIER_FREE("barrierFree"),
    @XmlEnumValue("shelter")
    SHELTER("shelter"),
    @XmlEnumValue("restroom")
    RESTROOM("restroom"),
    @XmlEnumValue("shopping")
    SHOPPING("shopping"),
    @XmlEnumValue("restaurant")
    RESTAURANT("restaurant"),
    @XmlEnumValue("baggageRoom")
    BAGGAGE_ROOM("baggageRoom"),
    @XmlEnumValue("bikeDepot")
    BIKE_DEPOT("bikeDepot"),
    @XmlEnumValue("bikeAccepted")
    BIKE_ACCEPTED("bikeAccepted"),
    @XmlEnumValue("parking")
    PARKING("parking");
    private final String value;

    PlaceEquipmentType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static PlaceEquipmentType fromValue(String v) {
        for (PlaceEquipmentType c: PlaceEquipmentType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
