//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteQualifierType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteQualifierType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="lastRoute"/>
 *     &lt;enumeration value="fastestRoute"/>
 *     &lt;enumeration value="shortestWalk"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteQualifierType")
@XmlEnum
public enum RouteQualifierType {

    @XmlEnumValue("lastRoute")
    LAST_ROUTE("lastRoute"),
    @XmlEnumValue("fastestRoute")
    FASTEST_ROUTE("fastestRoute"),
    @XmlEnumValue("shortestWalk")
    SHORTEST_WALK("shortestWalk");
    private final String value;

    RouteQualifierType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouteQualifierType fromValue(String v) {
        for (RouteQualifierType c: RouteQualifierType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
