connect 'jdbc:derby:/Users/ga/Library/Application Support/TrackIt/TrackItDB;create=true;';

drop table trackit.course_point;
drop table trackit.trackpoint;
drop table trackit.lap;
drop table trackit.session;
drop table trackit.event;
drop table trackit.device_info;
drop table trackit.activity_metadata;
drop table trackit.activity;
drop table trackit.course;
drop table trackit.document;

create table trackit.document
(
  id int not null generated always as identity (start with 1, increment by 1),
  name varchar(50) not null,
  filename varchar(150),
  constraint document_pk primary key (id)
);

create table trackit.course
(
  id int not null generated always as identity (start with 1, increment by 1),
  name varchar(20) not null,
  sport smallint not null,
  sub_sport smallint not null,
  notes varchar(250),
  elapsed_time int not null,
  timer_time int not null,
  moving_time int not null,
  paused_time int not null,
  distance int not null,
  average_speed int,
  average_moving_speed int,
  maximum_speed int,
  average_heart_rate smallint,
  minimum_heart_rate smallint,
  maximum_heart_rate smallint,
  average_cadence smallint,
  maximum_cadence smallint,
  average_running_cadence smallint,
  maximum_running_cadence smallint,
  average_power int,
  maximum_power int,
  calories int,
  fat_calories int,
  average_temperature smallint,
  minimum_temperature smallint,
  maximum_temperature smallint,
  total_ascent int,
  total_descent int,
  average_altitude int,
  minimum_altitude int,
  maximum_altitude int,
  average_grade int,
  average_positive_grade int,
  average_negative_grade int,
  maximum_positive_grade int,
  maximum_negative_grade int,
  average_positive_vertical_speed int,
  average_negative_vertical_speed int,
  maximum_positive_vertical_speed int,
  maximum_negative_vertical_speed int,
  start_longitude int not null,
  start_latitude int not null,
  start_altitude int,
  end_longitude int not null,
  end_latitude int not null,
  end_altitude int,
  northeast_longitude int,
  northeast_latitude int,
  southwest_longitude int,
  southwest_latitude int,
  document_id int,
  constraint course_pk primary key (id),
  constraint course_document_fk foreign key (document_id) references trackit.document (id)
);

create table trackit.activity
(
  id int not null generated always as identity (start with 1, increment by 1),
  name varchar(50) not null,
  notes varchar(250),
  start_time timestamp not null,
  end_time timestamp not null,
  timer_time int not null,
  type smallint not null,
  event smallint not null,
  event_type smallint not null,
  event_group smallint,
  document_id int,
  constraint activity_pk primary key (id),
  constraint activity_document_fk foreign key (document_id) references trackit.document (id)
);

create table trackit.activity_metadata
(
  id int not null generated always as identity (start with 1, increment by 1),
  recording_type smallint,
  manufacturer smallint,
  product smallint,
  serial_number bigint,
  time_created timestamp,
  software_version int,
  hardware_version smallint,
  activity_id int not null,
  constraint activity_metadata_pk primary key (id),
  constraint activity_metadata_activity_fk foreign key (activity_id) references trackit.activity (id)
);

create table trackit.device_info
(
  id int not null generated always as identity (start with 1, increment by 1),
  time timestamp not null,
  device_index smallint,
  device_type smallint,
  manufacturer smallint,
  product smallint,
  serial_number bigint,
  software_version int,
  hardware_version smallint,
  cummulative_operating_time bigint,
  battery_voltage int,
  battery_status smallint,
  activity_id int not null,
  constraint device_info_pk primary key (id),
  constraint device_info_activity_fk foreign key (activity_id) references trackit.activity (id)
);

create table trackit.event
(
  id int not null generated always as identity (start with 1, increment by 1),
  time timestamp not null,
  event smallint not null,
  event_type smallint not null,
  event_group smallint,
  timer_trigger smallint,
  battery_level int,
  activity_index int,
  session_index int,
  lap_index int,
  length_index int,
  course_point_index int,
  virtual_partner_speed int,
  heart_rate_low_alert smallint,
  heart_rate_high_alert smallint,
  cadence_low_alert int,
  cadence_high_alert int,
  speed_low_alert int,
  speed_high_alert int,
  power_low_alert int,
  power_high_alert int,
  time_duration_alert int,
  accumulated_time_duration_alert int,
  distance_duration_alert int,
  accumulated_distance_duration_alert int,
  calories_duration_alert int,
  accumulated_calories_duration_alert int,
  fitness_equipment_state smallint,
  recovery_heart_rate smallint,
  activity_id int,
  course_id int,
  constraint event_pk primary key (id),
  constraint event_activity_fk foreign key (activity_id) references trackit.activity (id),
  constraint event_course_fk foreign key (course_id) references trackit.course (id)
);

create table trackit.session
(
  id int not null generated always as identity (start with 1, increment by 1),
  start_time timestamp not null,
  end_time timestamp not null,
  trigger smallint not null,
  event smallint not null,
  event_type smallint not null,
  event_group smallint not null,
  start_longitude int,
  start_latitude int,
  start_altitude int,
  end_longitude int,
  end_latitude int,
  end_altitude int,
  sport smallint not null,
  sub_sport smallint not null,
  elapsed_time int not null,
  timer_time int not null,
  moving_time int not null,
  paused_time int not null,
  distance int not null,
  cycles int,
  strides int,
  calories smallint,
  fat_calories smallint,
  average_speed int,
  average_moving_speed int,
  maximum_speed int,
  average_heart_rate smallint,
  minimum_heart_rate smallint,
  maximum_heart_rate smallint,
  average_cadence smallint,
  maximum_cadence smallint,
  average_running_cadence smallint,
  maximum_running_cadence smallint,
  average_power smallint,
  maximum_power smallint,
  normalized_power smallint,
  left_right_balance smallint,
  total_ascent smallint,
  total_descent smallint,
  total_work int,
  training_effect smallint,
  training_stress_score smallint,
  intensity_factor smallint,
  average_stroke_count int,
  average_stroke_distance smallint,
  swim_stroke smallint,
  pool_length smallint,
  pool_length_unit smallint,
  number_active_lengths smallint,
  average_altitude int,
  minimum_altitude int,
  maximum_altitude int,
  altitude_difference int,
  average_grade smallint,
  average_positive_grade smallint,
  average_negative_grade smallint,
  maximum_positive_grade smallint,
  maximum_negative_grade smallint,
  average_temperature smallint,
  minimum_temperature smallint,
  maximum_temperature smallint,
  northeast_longitude int,
  northeast_latitude int,
  southwest_longitude int,
  southwest_latitude int,
  gps_accuracy smallint,
  average_lap_time int,
  best_lap_index smallint,
  activity_id int not null,
  constraint session_pk primary key (id),
  constraint session_activity_fk foreign key (activity_id) references trackit.activity (id)
);

create table trackit.lap
(
  id int not null generated always as identity (start with 1, increment by 1),
  start_time timestamp not null,
  end_time timestamp not null,
  trigger smallint not null,
  event smallint not null,
  event_type smallint not null,
  event_group smallint not null,
  start_longitude int,
  start_latitude int,
  start_altitude int,
  end_longitude int,
  end_latitude int,
  end_altitude int,
  sport smallint not null,
  sub_sport smallint not null,
  elapsed_time int not null,
  timer_time int not null,
  moving_time int not null,
  paused_time int not null,
  distance int not null,
  cycles int,
  strides int,
  calories smallint,
  fat_calories smallint,
  average_speed int,
  average_moving_speed int,
  maximum_speed int,
  average_heart_rate smallint,
  minimum_heart_rate smallint,
  maximum_heart_rate smallint,
  average_cadence smallint,
  maximum_cadence smallint,
  average_running_cadence smallint,
  maximum_running_cadence smallint,
  average_power smallint,
  maximum_power smallint,
  normalized_power smallint,
  left_right_balance smallint,
  total_ascent smallint,
  total_descent smallint,
  total_work int,
  average_stroke_distance smallint,
  swim_stroke smallint,
  number_active_lengths smallint,
  average_altitude int,
  minimum_altitude int,
  maximum_altitude int,
  altitude_difference int,
  average_grade smallint,
  average_positive_grade smallint,
  average_negative_grade smallint,
  maximum_positive_grade smallint,
  maximum_negative_grade smallint,
  average_temperature smallint,
  minimum_temperature smallint,
  maximum_temperature smallint,
  northeast_longitude int,
  northeast_latitude int,
  southwest_longitude int,
  southwest_latitude int,
  gps_accuracy smallint,
  notes varchar(250),
  activity_id int,
  course_id int,
  constraint lap_pk primary key (id),
  constraint lap_activity_fk foreign key (activity_id) references trackit.activity (id),
  constraint lap_course_fk foreign key (course_id) references trackit.course (id)
);

create table trackit.trackpoint
(
  id bigint not null generated always as identity (start with 1, increment by 1),
  timestamp timestamp not null,
  time_from_previous int,
  distance int,
  distance_from_previous int,
  longitude int not null,
  latitude int not null,
  altitude int,
  speed int,
  heart_rate smallint,
  cadence smallint,
  power smallint,
  grade smallint,
  resistance smallint,
  time_from_course int,
  temperature smallint,
  cycles int,
  total_cycles int,
  left_right_balance smallint,
  gps_accuracy smallint,
  vertical_speed int,
  calories smallint,
  activity_id int,
  course_id int,
  constraint trackpoint_pk primary key (id),
  constraint trackpoint_activity_fk foreign key (activity_id) references trackit.activity (id),
  constraint trackpoint_course_fk foreign key (course_id) references trackit.course (id)
);

create table trackit.course_point
(
  id bigint not null generated always as identity (start with 1, increment by 1),
  name varchar(20) not null,
  type smallint not null,
  time timestamp not null,
  distance int not null,
  longitude int not null,
  latitude int not null,
  altitude int,
  notes varchar(250),
  course_id int not null,
  constraint couse_point_pk primary key (id),
  constraint course_point_course_fk foreign key (course_id) references trackit.course (id)
);

create index trackpoint_lon_lat_index on trackit.trackpoint(longitude, latitude);

disconnect;
exit;
