//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcommon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Dynamic speed information on the link which can change over time.
 * 
 * <p>Java class for DynamicSpeedInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="DynamicSpeedInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrafficSpeed" type="{http://www.navteq.com/lbsp/Common/4}SpeedType" minOccurs="0"/>
 *         &lt;element name="TrafficTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="BaseSpeed" type="{http://www.navteq.com/lbsp/Common/4}SpeedType"/>
 *         &lt;element name="BaseTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType"/>
 *         &lt;element name="JamFactor" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="JamFactorTrend" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Confidence" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "DynamicSpeedInfoType", propOrder = {
    "trafficSpeed",
    "trafficTime",
    "baseSpeed",
    "baseTime",
    "jamFactor",
    "jamFactorTrend",
    "confidence"
})
public class DynamicSpeedInfoType {

    @XmlElement(name = "TrafficSpeed")
    protected Double trafficSpeed;
    @XmlElement(name = "TrafficTime")
    protected Double trafficTime;
    @XmlElement(name = "BaseSpeed")
    protected double baseSpeed;
    @XmlElement(name = "BaseTime")
    protected double baseTime;
    @XmlElement(name = "JamFactor")
    protected Double jamFactor;
    @XmlElement(name = "JamFactorTrend")
    protected Double jamFactorTrend;
    @XmlElement(name = "Confidence")
    protected Double confidence;

    /**
     * Gets the value of the trafficSpeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTrafficSpeed() {
        return trafficSpeed;
    }

    /**
     * Sets the value of the trafficSpeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTrafficSpeed(Double value) {
        this.trafficSpeed = value;
    }

    /**
     * Gets the value of the trafficTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTrafficTime() {
        return trafficTime;
    }

    /**
     * Sets the value of the trafficTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTrafficTime(Double value) {
        this.trafficTime = value;
    }

    /**
     * Gets the value of the baseSpeed property.
     * 
     */
    public double getBaseSpeed() {
        return baseSpeed;
    }

    /**
     * Sets the value of the baseSpeed property.
     * 
     */
    public void setBaseSpeed(double value) {
        this.baseSpeed = value;
    }

    /**
     * Gets the value of the baseTime property.
     * 
     */
    public double getBaseTime() {
        return baseTime;
    }

    /**
     * Sets the value of the baseTime property.
     * 
     */
    public void setBaseTime(double value) {
        this.baseTime = value;
    }

    /**
     * Gets the value of the jamFactor property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJamFactor() {
        return jamFactor;
    }

    /**
     * Sets the value of the jamFactor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJamFactor(Double value) {
        this.jamFactor = value;
    }

    /**
     * Gets the value of the jamFactorTrend property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getJamFactorTrend() {
        return jamFactorTrend;
    }

    /**
     * Sets the value of the jamFactorTrend property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setJamFactorTrend(Double value) {
        this.jamFactorTrend = value;
    }

    /**
     * Gets the value of the confidence property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getConfidence() {
        return confidence;
    }

    /**
     * Sets the value of the confidence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setConfidence(Double value) {
        this.confidence = value;
    }

}
