//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcommon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The LinkPosition is used to define an accurate position on a link.
 * 
 * <p>Java class for LinkPositionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LinkPositionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LinkId" type="{http://www.navteq.com/lbsp/Common/4}LinkIdType"/>
 *         &lt;element name="Spot" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="SideOfStreet" type="{http://www.navteq.com/lbsp/Common/4}SideOfStreetType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LinkPositionType", propOrder = {
    "linkId",
    "spot",
    "sideOfStreet"
})
public class LinkPositionType {

    @XmlElement(name = "LinkId", required = true)
    protected String linkId;
    @XmlElement(name = "Spot")
    protected Double spot;
    @XmlElement(name = "SideOfStreet", required = true)
    protected SideOfStreetType sideOfStreet;

    /**
     * Gets the value of the linkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkId() {
        return linkId;
    }

    /**
     * Sets the value of the linkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkId(String value) {
        this.linkId = value;
    }

    /**
     * Gets the value of the spot property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getSpot() {
        return spot;
    }

    /**
     * Sets the value of the spot property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setSpot(Double value) {
        this.spot = value;
    }

    /**
     * Gets the value of the sideOfStreet property.
     * 
     * @return
     *     possible object is
     *     {@link SideOfStreetType }
     *     
     */
    public SideOfStreetType getSideOfStreet() {
        return sideOfStreet;
    }

    /**
     * Sets the value of the sideOfStreet property.
     * 
     * @param value
     *     allowed object is
     *     {@link SideOfStreetType }
     *     
     */
    public void setSideOfStreet(SideOfStreetType value) {
        this.sideOfStreet = value;
    }

}
