//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * The PositioningWaypointParameter is used to define a waypoint based on the data provided by a GPS device. A list of measurements are passed as input to a map matching algorithm.
 * <i>Note: not yet supported</i>
 * 
 * <p>Java class for PositioningWaypointParameterType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PositioningWaypointParameterType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navteq.com/lbsp/Routing-Common/4}WaypointParameterType">
 *       &lt;sequence>
 *         &lt;element name="PositionHistory" type="{http://www.navteq.com/lbsp/Routing-Common/4}GeoPositionLogType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PositioningWaypointParameterType", propOrder = {
    "positionHistory"
})
public class PositioningWaypointParameterType
    extends WaypointParameterType
{

    @XmlElement(name = "PositionHistory")
    protected List<GeoPositionLogType> positionHistory;

    /**
     * Gets the value of the positionHistory property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the positionHistory property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPositionHistory().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoPositionLogType }
     * 
     * 
     */
    public List<GeoPositionLogType> getPositionHistory() {
        if (positionHistory == null) {
            positionHistory = new ArrayList<GeoPositionLogType>();
        }
        return this.positionHistory;
    }

}
