//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * This type represents a maneuver relevant for private transport such as car, truck, pedestrian. This type is derived from the abstract typeManueverType.
 * 
 * <p>Java class for PrivateTransportManeuverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PrivateTransportManeuverType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navteq.com/lbsp/Routing-Common/4}ManeuverType">
 *       &lt;sequence>
 *         &lt;element name="Direction" type="{http://www.navteq.com/lbsp/Routing-Common/4}DirectionType" minOccurs="0"/>
 *         &lt;element name="Action" type="{http://www.navteq.com/lbsp/Routing-Common/4}PrivateTransportActionType" minOccurs="0"/>
 *         &lt;element name="RoadName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SignPost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NextRoadName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="RoadNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="NextRoadNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Lane" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteLaneType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SelectedLanes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.w3.org/2001/XMLSchema}int" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="RoadTemplate" type="{http://www.navteq.com/lbsp/Routing-Common/4}ExternalResourceType" minOccurs="0"/>
 *         &lt;element name="NavigationSignPost" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="IntersectionIcon" type="{http://www.navteq.com/lbsp/Routing-Common/4}IntersectionIconType" minOccurs="0"/>
 *         &lt;element name="FreewayExit" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="FreewayJunction" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="TrafficTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="BaseTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="RoadShield" type="{http://www.navteq.com/lbsp/Routing-Common/4}RoadShieldType" minOccurs="0"/>
 *         &lt;element name="StartAngle" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PrivateTransportManeuverType", propOrder = {
    "direction",
    "action",
    "roadName",
    "signPost",
    "nextRoadName",
    "roadNumber",
    "nextRoadNumber",
    "lane",
    "selectedLanes",
    "roadTemplate",
    "navigationSignPost",
    "intersectionIcon",
    "freewayExit",
    "freewayJunction",
    "trafficTime",
    "baseTime",
    "roadShield",
    "startAngle"
})
public class PrivateTransportManeuverType
    extends ManeuverType
{

    @XmlElement(name = "Direction")
    protected DirectionType direction;
    @XmlElement(name = "Action")
    protected PrivateTransportActionType action;
    @XmlElement(name = "RoadName")
    protected String roadName;
    @XmlElement(name = "SignPost")
    protected String signPost;
    @XmlElement(name = "NextRoadName")
    protected String nextRoadName;
    @XmlElement(name = "RoadNumber")
    protected String roadNumber;
    @XmlElement(name = "NextRoadNumber")
    protected String nextRoadNumber;
    @XmlElement(name = "Lane")
    protected List<RouteLaneType> lane;
    @XmlList
    @XmlElement(name = "SelectedLanes", type = Integer.class)
    protected List<Integer> selectedLanes;
    @XmlElement(name = "RoadTemplate")
    protected ExternalResourceType roadTemplate;
    @XmlElement(name = "NavigationSignPost")
    protected String navigationSignPost;
    @XmlElement(name = "IntersectionIcon")
    protected IntersectionIconType intersectionIcon;
    @XmlElement(name = "FreewayExit")
    protected String freewayExit;
    @XmlElement(name = "FreewayJunction")
    protected String freewayJunction;
    @XmlElement(name = "TrafficTime")
    protected Double trafficTime;
    @XmlElement(name = "BaseTime")
    protected Double baseTime;
    @XmlElement(name = "RoadShield")
    protected RoadShieldType roadShield;
    @XmlElement(name = "StartAngle")
    protected Integer startAngle;

    /**
     * Gets the value of the direction property.
     * 
     * @return
     *     possible object is
     *     {@link DirectionType }
     *     
     */
    public DirectionType getDirection() {
        return direction;
    }

    /**
     * Sets the value of the direction property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectionType }
     *     
     */
    public void setDirection(DirectionType value) {
        this.direction = value;
    }

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link PrivateTransportActionType }
     *     
     */
    public PrivateTransportActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrivateTransportActionType }
     *     
     */
    public void setAction(PrivateTransportActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the roadName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadName() {
        return roadName;
    }

    /**
     * Sets the value of the roadName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadName(String value) {
        this.roadName = value;
    }

    /**
     * Gets the value of the signPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSignPost() {
        return signPost;
    }

    /**
     * Sets the value of the signPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSignPost(String value) {
        this.signPost = value;
    }

    /**
     * Gets the value of the nextRoadName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextRoadName() {
        return nextRoadName;
    }

    /**
     * Sets the value of the nextRoadName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextRoadName(String value) {
        this.nextRoadName = value;
    }

    /**
     * Gets the value of the roadNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoadNumber() {
        return roadNumber;
    }

    /**
     * Sets the value of the roadNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoadNumber(String value) {
        this.roadNumber = value;
    }

    /**
     * Gets the value of the nextRoadNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextRoadNumber() {
        return nextRoadNumber;
    }

    /**
     * Sets the value of the nextRoadNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextRoadNumber(String value) {
        this.nextRoadNumber = value;
    }

    /**
     * Gets the value of the lane property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lane property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLane().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteLaneType }
     * 
     * 
     */
    public List<RouteLaneType> getLane() {
        if (lane == null) {
            lane = new ArrayList<RouteLaneType>();
        }
        return this.lane;
    }

    /**
     * Gets the value of the selectedLanes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the selectedLanes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getSelectedLanes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Integer }
     * 
     * 
     */
    public List<Integer> getSelectedLanes() {
        if (selectedLanes == null) {
            selectedLanes = new ArrayList<Integer>();
        }
        return this.selectedLanes;
    }

    /**
     * Gets the value of the roadTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalResourceType }
     *     
     */
    public ExternalResourceType getRoadTemplate() {
        return roadTemplate;
    }

    /**
     * Sets the value of the roadTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalResourceType }
     *     
     */
    public void setRoadTemplate(ExternalResourceType value) {
        this.roadTemplate = value;
    }

    /**
     * Gets the value of the navigationSignPost property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNavigationSignPost() {
        return navigationSignPost;
    }

    /**
     * Sets the value of the navigationSignPost property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNavigationSignPost(String value) {
        this.navigationSignPost = value;
    }

    /**
     * Gets the value of the intersectionIcon property.
     * 
     * @return
     *     possible object is
     *     {@link IntersectionIconType }
     *     
     */
    public IntersectionIconType getIntersectionIcon() {
        return intersectionIcon;
    }

    /**
     * Sets the value of the intersectionIcon property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntersectionIconType }
     *     
     */
    public void setIntersectionIcon(IntersectionIconType value) {
        this.intersectionIcon = value;
    }

    /**
     * Gets the value of the freewayExit property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreewayExit() {
        return freewayExit;
    }

    /**
     * Sets the value of the freewayExit property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreewayExit(String value) {
        this.freewayExit = value;
    }

    /**
     * Gets the value of the freewayJunction property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFreewayJunction() {
        return freewayJunction;
    }

    /**
     * Sets the value of the freewayJunction property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFreewayJunction(String value) {
        this.freewayJunction = value;
    }

    /**
     * Gets the value of the trafficTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTrafficTime() {
        return trafficTime;
    }

    /**
     * Sets the value of the trafficTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTrafficTime(Double value) {
        this.trafficTime = value;
    }

    /**
     * Gets the value of the baseTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getBaseTime() {
        return baseTime;
    }

    /**
     * Sets the value of the baseTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setBaseTime(Double value) {
        this.baseTime = value;
    }

    /**
     * Gets the value of the roadShield property.
     * 
     * @return
     *     possible object is
     *     {@link RoadShieldType }
     *     
     */
    public RoadShieldType getRoadShield() {
        return roadShield;
    }

    /**
     * Sets the value of the roadShield property.
     * 
     * @param value
     *     allowed object is
     *     {@link RoadShieldType }
     *     
     */
    public void setRoadShield(RoadShieldType value) {
        this.roadShield = value;
    }

    /**
     * Gets the value of the startAngle property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartAngle() {
        return startAngle;
    }

    /**
     * Sets the value of the startAngle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartAngle(Integer value) {
        this.startAngle = value;
    }

}
