//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines the information available for a public transport line.
 * 
 * <p>Java class for PublicTransportLineType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicTransportLineType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="LineName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LineForeground" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LineBackground" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LineStyle" type="{http://www.navteq.com/lbsp/Routing-Common/4}LineStyleType" minOccurs="0"/>
 *         &lt;element name="CompanyName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="CompanyShortName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyLogo" type="{http://www.navteq.com/lbsp/Routing-Common/4}ExternalResourceType" minOccurs="0"/>
 *         &lt;element name="Destination" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Flags" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportLinkFlagType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Type" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportTypeType"/>
 *         &lt;element name="TypeName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="LineId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="CompanyId" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="SystemId" type="{http://www.navteq.com/lbsp/Common/4}TransitSystemIdType" minOccurs="0"/>
 *         &lt;element name="Stop" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportStopType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="id1" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType"/>
 *       &lt;/sequence>
 *       &lt;attribute name="id2" use="required" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicTransportLineType", propOrder = {
    "lineName",
    "lineForeground",
    "lineBackground",
    "lineStyle",
    "companyName",
    "companyShortName",
    "companyLogo",
    "destination",
    "flags",
    "type",
    "typeName",
    "lineId",
    "companyId",
    "systemId",
    "stop",
    "id1"
})
public class PublicTransportLineType {

    @XmlElement(name = "LineName", required = true)
    protected String lineName;
    @XmlElement(name = "LineForeground")
    protected String lineForeground;
    @XmlElement(name = "LineBackground")
    protected String lineBackground;
    @XmlElement(name = "LineStyle")
    protected LineStyleType lineStyle;
    @XmlElement(name = "CompanyName", required = true)
    protected String companyName;
    @XmlElement(name = "CompanyShortName")
    protected String companyShortName;
    @XmlElement(name = "CompanyLogo")
    protected ExternalResourceType companyLogo;
    @XmlElement(name = "Destination", required = true)
    protected String destination;
    @XmlElement(name = "Flags")
    protected List<PublicTransportLinkFlagType> flags;
    @XmlElement(name = "Type", required = true)
    protected PublicTransportTypeType type;
    @XmlElement(name = "TypeName")
    protected String typeName;
    @XmlElement(name = "LineId")
    protected String lineId;
    @XmlElement(name = "CompanyId")
    protected String companyId;
    @XmlElement(name = "SystemId")
    protected String systemId;
    @XmlElement(name = "Stop")
    protected List<PublicTransportStopType> stop;
    @XmlElement(required = true)
    protected String id1;
    @XmlAttribute(name = "id2", required = true)
    protected String id2;

    /**
     * Gets the value of the lineName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineName() {
        return lineName;
    }

    /**
     * Sets the value of the lineName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineName(String value) {
        this.lineName = value;
    }

    /**
     * Gets the value of the lineForeground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineForeground() {
        return lineForeground;
    }

    /**
     * Sets the value of the lineForeground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineForeground(String value) {
        this.lineForeground = value;
    }

    /**
     * Gets the value of the lineBackground property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineBackground() {
        return lineBackground;
    }

    /**
     * Sets the value of the lineBackground property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineBackground(String value) {
        this.lineBackground = value;
    }

    /**
     * Gets the value of the lineStyle property.
     * 
     * @return
     *     possible object is
     *     {@link LineStyleType }
     *     
     */
    public LineStyleType getLineStyle() {
        return lineStyle;
    }

    /**
     * Sets the value of the lineStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link LineStyleType }
     *     
     */
    public void setLineStyle(LineStyleType value) {
        this.lineStyle = value;
    }

    /**
     * Gets the value of the companyName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * Sets the value of the companyName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyName(String value) {
        this.companyName = value;
    }

    /**
     * Gets the value of the companyShortName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyShortName() {
        return companyShortName;
    }

    /**
     * Sets the value of the companyShortName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyShortName(String value) {
        this.companyShortName = value;
    }

    /**
     * Gets the value of the companyLogo property.
     * 
     * @return
     *     possible object is
     *     {@link ExternalResourceType }
     *     
     */
    public ExternalResourceType getCompanyLogo() {
        return companyLogo;
    }

    /**
     * Sets the value of the companyLogo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExternalResourceType }
     *     
     */
    public void setCompanyLogo(ExternalResourceType value) {
        this.companyLogo = value;
    }

    /**
     * Gets the value of the destination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDestination() {
        return destination;
    }

    /**
     * Sets the value of the destination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDestination(String value) {
        this.destination = value;
    }

    /**
     * Gets the value of the flags property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the flags property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFlags().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportLinkFlagType }
     * 
     * 
     */
    public List<PublicTransportLinkFlagType> getFlags() {
        if (flags == null) {
            flags = new ArrayList<PublicTransportLinkFlagType>();
        }
        return this.flags;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link PublicTransportTypeType }
     *     
     */
    public PublicTransportTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicTransportTypeType }
     *     
     */
    public void setType(PublicTransportTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the typeName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * Sets the value of the typeName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTypeName(String value) {
        this.typeName = value;
    }

    /**
     * Gets the value of the lineId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineId() {
        return lineId;
    }

    /**
     * Sets the value of the lineId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineId(String value) {
        this.lineId = value;
    }

    /**
     * Gets the value of the companyId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * Sets the value of the companyId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyId(String value) {
        this.companyId = value;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the stop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the stop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getStop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportStopType }
     * 
     * 
     */
    public List<PublicTransportStopType> getStop() {
        if (stop == null) {
            stop = new ArrayList<PublicTransportStopType>();
        }
        return this.stop;
    }

    /**
     * Gets the value of the id1 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId1() {
        return id1;
    }

    /**
     * Sets the value of the id1 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId1(String value) {
        this.id1 = value;
    }

    /**
     * Gets the value of the id2 property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId2() {
        return id2;
    }

    /**
     * Sets the value of the id2 property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId2(String value) {
        this.id2 = value;
    }

}
