//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * This type represents a maneuver relevant for public transport such as bus, train. This type is derived from the abstract type ManueverType.
 * Two different types of public transport maneuvers are supported: "Enter" and "Leave" (see enumeration type <b>PublicTransportAction</b>). A direct change between two transport lines will be represented with two maneuvers: one for the action "Leave" and a subsequent one to "Enter" the next transport line.
 * 
 * <p>Java class for PublicTransportManeuverType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicTransportManeuverType">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.navteq.com/lbsp/Routing-Common/4}ManeuverType">
 *       &lt;sequence>
 *         &lt;element name="Action" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportActionType" minOccurs="0"/>
 *         &lt;element name="StopName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="PlatformName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="PlatformLevel" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Line" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="ToLine" type="{http://www.navteq.com/lbsp/Common/4}ElementReferenceType" minOccurs="0"/>
 *         &lt;element name="StopId" type="{http://www.navteq.com/lbsp/Common/4}TransitStopIdType" minOccurs="0"/>
 *         &lt;element name="AccessPointName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="AccesPointId" type="{http://www.navteq.com/lbsp/Common/4}TransitAccessIdType" minOccurs="0"/>
 *         &lt;element name="NextRoadName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="WaitTime" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicTransportManeuverType", propOrder = {
    "action",
    "stopName",
    "platformName",
    "platformLevel",
    "line",
    "toLine",
    "stopId",
    "accessPointName",
    "accesPointId",
    "nextRoadName",
    "waitTime"
})
public class PublicTransportManeuverType
    extends ManeuverType
{

    @XmlElement(name = "Action")
    protected PublicTransportActionType action;
    @XmlElement(name = "StopName", required = true)
    protected String stopName;
    @XmlElement(name = "PlatformName")
    protected String platformName;
    @XmlElement(name = "PlatformLevel")
    protected String platformLevel;
    @XmlElement(name = "Line")
    protected String line;
    @XmlElement(name = "ToLine")
    protected String toLine;
    @XmlElement(name = "StopId")
    protected String stopId;
    @XmlElement(name = "AccessPointName")
    protected String accessPointName;
    @XmlElement(name = "AccesPointId")
    protected String accesPointId;
    @XmlElement(name = "NextRoadName")
    protected String nextRoadName;
    @XmlElement(name = "WaitTime")
    protected Double waitTime;

    /**
     * Gets the value of the action property.
     * 
     * @return
     *     possible object is
     *     {@link PublicTransportActionType }
     *     
     */
    public PublicTransportActionType getAction() {
        return action;
    }

    /**
     * Sets the value of the action property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicTransportActionType }
     *     
     */
    public void setAction(PublicTransportActionType value) {
        this.action = value;
    }

    /**
     * Gets the value of the stopName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopName() {
        return stopName;
    }

    /**
     * Sets the value of the stopName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopName(String value) {
        this.stopName = value;
    }

    /**
     * Gets the value of the platformName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformName() {
        return platformName;
    }

    /**
     * Sets the value of the platformName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformName(String value) {
        this.platformName = value;
    }

    /**
     * Gets the value of the platformLevel property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPlatformLevel() {
        return platformLevel;
    }

    /**
     * Sets the value of the platformLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPlatformLevel(String value) {
        this.platformLevel = value;
    }

    /**
     * Gets the value of the line property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLine() {
        return line;
    }

    /**
     * Sets the value of the line property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLine(String value) {
        this.line = value;
    }

    /**
     * Gets the value of the toLine property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToLine() {
        return toLine;
    }

    /**
     * Sets the value of the toLine property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToLine(String value) {
        this.toLine = value;
    }

    /**
     * Gets the value of the stopId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStopId() {
        return stopId;
    }

    /**
     * Sets the value of the stopId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStopId(String value) {
        this.stopId = value;
    }

    /**
     * Gets the value of the accessPointName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccessPointName() {
        return accessPointName;
    }

    /**
     * Sets the value of the accessPointName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccessPointName(String value) {
        this.accessPointName = value;
    }

    /**
     * Gets the value of the accesPointId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAccesPointId() {
        return accesPointId;
    }

    /**
     * Sets the value of the accesPointId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAccesPointId(String value) {
        this.accesPointId = value;
    }

    /**
     * Gets the value of the nextRoadName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNextRoadName() {
        return nextRoadName;
    }

    /**
     * Sets the value of the nextRoadName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNextRoadName(String value) {
        this.nextRoadName = value;
    }

    /**
     * Gets the value of the waitTime property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWaitTime() {
        return waitTime;
    }

    /**
     * Sets the value of the waitTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWaitTime(Double value) {
        this.waitTime = value;
    }

}
