//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteLinkAttributeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteLinkAttributeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="shape"/>
 *     &lt;enumeration value="length"/>
 *     &lt;enumeration value="speedLimit"/>
 *     &lt;enumeration value="dynamicSpeedInfo"/>
 *     &lt;enumeration value="incidents"/>
 *     &lt;enumeration value="truckRestrictions"/>
 *     &lt;enumeration value="externalResources"/>
 *     &lt;enumeration value="flags"/>
 *     &lt;enumeration value="address"/>
 *     &lt;enumeration value="roadNumber"/>
 *     &lt;enumeration value="roadName"/>
 *     &lt;enumeration value="freewayExit"/>
 *     &lt;enumeration value="freewayJunction"/>
 *     &lt;enumeration value="timezone"/>
 *     &lt;enumeration value="corridorLevel"/>
 *     &lt;enumeration value="nextLink"/>
 *     &lt;enumeration value="stubs"/>
 *     &lt;enumeration value="publicTransportLine"/>
 *     &lt;enumeration value="TMCCodes"/>
 *     &lt;enumeration value="jamFactor"/>
 *     &lt;enumeration value="jamFactorTrend"/>
 *     &lt;enumeration value="confidence"/>
 *     &lt;enumeration value="remainTime"/>
 *     &lt;enumeration value="remainDistance"/>
 *     &lt;enumeration value="maneuver"/>
 *     &lt;enumeration value="functionalClass"/>
 *     &lt;enumeration value="nextStopName"/>
 *     &lt;enumeration value="additionalData"/>
 *     &lt;enumeration value="speedCategory"/>
 *     &lt;enumeration value="successors"/>
 *     &lt;enumeration value="predecessors"/>
 *     &lt;enumeration value="indices"/>
 *     &lt;enumeration value="compressedShapes"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteLinkAttributeType")
@XmlEnum
public enum RouteLinkAttributeType {


    /**
     * Short value: "sh". Indicates whether the link should include its geometry
     * 
     */
    @XmlEnumValue("shape")
    SHAPE("shape"),

    /**
     * Short value: "le". Indicates whether the link should include its length
     * 
     */
    @XmlEnumValue("length")
    LENGTH("length"),

    /**
     * Short value: "sl". Indicates whether the link should include SpeedLimit
     * 
     */
    @XmlEnumValue("speedLimit")
    SPEED_LIMIT("speedLimit"),

    /**
     * Short value: "ds". Indicates whether the link should include dynamic speed information
     * 
     */
    @XmlEnumValue("dynamicSpeedInfo")
    DYNAMIC_SPEED_INFO("dynamicSpeedInfo"),

    /**
     * Short value: "ic". Indicates whether the link should include incidents
     * 
     */
    @XmlEnumValue("incidents")
    INCIDENTS("incidents"),

    /**
     * Short value: "tr". Indicates whether the link should include truck restrictions
     * 
     */
    @XmlEnumValue("truckRestrictions")
    TRUCK_RESTRICTIONS("truckRestrictions"),

    /**
     * Short value: "er". Indicates whether the link should include external resources
     * 
     */
    @XmlEnumValue("externalResources")
    EXTERNAL_RESOURCES("externalResources"),

    /**
     * Short value: "fl". Indicates whether the link should include link flags
     * 
     */
    @XmlEnumValue("flags")
    FLAGS("flags"),

    /**
     * Short value: "ad". Indicates whether the link should include the link's address
     * 
     */
    @XmlEnumValue("address")
    ADDRESS("address"),

    /**
     * Short value: "rn". Indicates whether the link should include the link's road number
     * 
     */
    @XmlEnumValue("roadNumber")
    ROAD_NUMBER("roadNumber"),

    /**
     * Short value: "ro". Indicates whether the link should include the link's road number
     * 
     */
    @XmlEnumValue("roadName")
    ROAD_NAME("roadName"),

    /**
     * Short value: "fe". Indicates whether the link should include the name of the freeway exit
     * 
     */
    @XmlEnumValue("freewayExit")
    FREEWAY_EXIT("freewayExit"),

    /**
     * Short value: "fj". Indicates whether the link should include the name of the freeway junction
     * 
     */
    @XmlEnumValue("freewayJunction")
    FREEWAY_JUNCTION("freewayJunction"),

    /**
     * Short value: "tz". Indicates whether the link should include the timezone
     * 
     */
    @XmlEnumValue("timezone")
    TIMEZONE("timezone"),

    /**
     * Short value: "cl". Indicates whether the link should include the corridor level
     * 
     */
    @XmlEnumValue("corridorLevel")
    CORRIDOR_LEVEL("corridorLevel"),

    /**
     * Short value: "nl". Indicates whether the link should include the link which will be next when following the route
     * 
     */
    @XmlEnumValue("nextLink")
    NEXT_LINK("nextLink"),

    /**
     * Short value: "st". Indicates whether the link should include the corridor stubs
     * 
     */
    @XmlEnumValue("stubs")
    STUBS("stubs"),

    /**
     * Short value: "pt". Indicates whether the link should include information about the public transport line.
     * 
     */
    @XmlEnumValue("publicTransportLine")
    PUBLIC_TRANSPORT_LINE("publicTransportLine"),

    /**
     * Short value: "tm". Indicates whether the link should include information about the covered TMC Codes.
     * 
     */
    @XmlEnumValue("TMCCodes")
    TMC_CODES("TMCCodes"),

    /**
     * Short value: "jf". Indicates whether the link's dynamic speed info should include information about the jam factor.
     * 
     */
    @XmlEnumValue("jamFactor")
    JAM_FACTOR("jamFactor"),

    /**
     * Short value: "jt". Indicates whether the link's dynamic speed info should include information about the jam factor trend.
     * 
     */
    @XmlEnumValue("jamFactorTrend")
    JAM_FACTOR_TREND("jamFactorTrend"),

    /**
     * Short value: "co". Indicates whether the link's dynamic speed info should include information about the level of confidence wrt. traffic information.
     * 
     */
    @XmlEnumValue("confidence")
    CONFIDENCE("confidence"),

    /**
     * Short value: "rt". Indicates whether the link should include information about the remaining time until the destination is reached.
     * 
     */
    @XmlEnumValue("remainTime")
    REMAIN_TIME("remainTime"),

    /**
     * Short value: "rd". Indicates whether the link should include information about the remaining distance until the destination is reached.
     * 
     */
    @XmlEnumValue("remainDistance")
    REMAIN_DISTANCE("remainDistance"),

    /**
     * Short value: "ma". Indicates whether the link should include information about the associated maneuver.
     * 
     */
    @XmlEnumValue("maneuver")
    MANEUVER("maneuver"),

    /**
     * Short value: "fc". Indicates whether the link should include information about the functional class.
     * 
     */
    @XmlEnumValue("functionalClass")
    FUNCTIONAL_CLASS("functionalClass"),

    /**
     * Short value: "ns". Indicates whether the link should include information about the next stop.
     * 
     */
    @XmlEnumValue("nextStopName")
    NEXT_STOP_NAME("nextStopName"),

    /**
     * Short value: "dd". Indicates whether the link should include the container for additional data.
     * 
     */
    @XmlEnumValue("additionalData")
    ADDITIONAL_DATA("additionalData"),

    /**
     * Short value: "sc". Indicates whether the link should include speed category information.
     * 
     */
    @XmlEnumValue("speedCategory")
    SPEED_CATEGORY("speedCategory"),

    /**
     * Short value: "su". Indicates whether the link should include successor link ID information.
     * 
     */
    @XmlEnumValue("successors")
    SUCCESSORS("successors"),

    /**
     * Short value: "pr". Indicates whether the link should include predecessor link ID information.
     * 
     */
    @XmlEnumValue("predecessors")
    PREDECESSORS("predecessors"),

    /**
     * Short value: "ix": Indicates whether shape index information (FirstPoint, LastPoint) should be included in the links instead of copying shape points to the link.
     * 
     */
    @XmlEnumValue("indices")
    INDICES("indices"),

    /**
     * Short value: "sz": Indicates whether compressed shape information should be included in links. Shape compression may considerably reduce the amount of data transferred.
     * 
     */
    @XmlEnumValue("compressedShapes")
    COMPRESSED_SHAPES("compressedShapes");
    private final String value;

    RouteLinkAttributeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouteLinkAttributeType fromValue(String v) {
        for (RouteLinkAttributeType c: RouteLinkAttributeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
