//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteLinkFlagType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteLinkFlagType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="tollroad"/>
 *     &lt;enumeration value="motorway"/>
 *     &lt;enumeration value="boatFerry"/>
 *     &lt;enumeration value="railFerry"/>
 *     &lt;enumeration value="publicTransport"/>
 *     &lt;enumeration value="tunnel"/>
 *     &lt;enumeration value="dirtRoad"/>
 *     &lt;enumeration value="park"/>
 *     &lt;enumeration value="HOVLane"/>
 *     &lt;enumeration value="stairs"/>
 *     &lt;enumeration value="railFerry"/>
 *     &lt;enumeration value="boatFerry"/>
 *     &lt;enumeration value="gatedArea"/>
 *     &lt;enumeration value="privateRoad"/>
 *     &lt;enumeration value="station"/>
 *     &lt;enumeration value="unpaved"/>
 *     &lt;enumeration value="fourWheelDrive"/>
 *     &lt;enumeration value="noThroughRoad"/>
 *     &lt;enumeration value="scenic"/>
 *     &lt;enumeration value="builtUpArea"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteLinkFlagType")
@XmlEnum
public enum RouteLinkFlagType {


    /**
     * Link is part of a toll road
     * 
     */
    @XmlEnumValue("tollroad")
    TOLLROAD("tollroad"),

    /**
     * Link is part of a motorway
     * 
     */
    @XmlEnumValue("motorway")
    MOTORWAY("motorway"),

    /**
     * Link can only be traversed by using a boat ferry
     * 
     */
    @XmlEnumValue("boatFerry")
    BOAT_FERRY("boatFerry"),

    /**
     * Link can only be traversed by using a rail ferry
     * 
     */
    @XmlEnumValue("railFerry")
    RAIL_FERRY("railFerry"),

    /**
     * Link is part of a public transport connection
     * 
     */
    @XmlEnumValue("publicTransport")
    PUBLIC_TRANSPORT("publicTransport"),

    /**
     * Link passes through a tunnel
     * 
     */
    @XmlEnumValue("tunnel")
    TUNNEL("tunnel"),

    /**
     * Link is part of a dirt road
     * 
     */
    @XmlEnumValue("dirtRoad")
    DIRT_ROAD("dirtRoad"),

    /**
     * Link is part of a park
     * 
     */
    @XmlEnumValue("park")
    PARK("park"),

    /**
     * Link can only be traversed by using high-occupancy vehicle (HOV) lanes
     * 
     */
    @XmlEnumValue("HOVLane")
    HOV_LANE("HOVLane"),

    /**
     * Link can only be traversed by using stairs
     * 
     */
    @XmlEnumValue("stairs")
    STAIRS("stairs"),

    /**
     * Link is part of a gated area
     * 
     */
    @XmlEnumValue("gatedArea")
    GATED_AREA("gatedArea"),

    /**
     * Link is part of a private road
     * 
     */
    @XmlEnumValue("privateRoad")
    PRIVATE_ROAD("privateRoad"),

    /**
     * Link is located at a station
     * 
     */
    @XmlEnumValue("station")
    STATION("station"),

    /**
     * Link is part of an unpaved road
     * 
     */
    @XmlEnumValue("unpaved")
    UNPAVED("unpaved"),

    /**
     * Link is part of a road that is suitable only for vehicles with four-wheel drive
     * 
     */
    @XmlEnumValue("fourWheelDrive")
    FOUR_WHEEL_DRIVE("fourWheelDrive"),

    /**
     * Link is part of a road that you can enter but you have to exit the same way
     * 
     */
    @XmlEnumValue("noThroughRoad")
    NO_THROUGH_ROAD("noThroughRoad"),

    /**
     * Link is part of a road that has been marked as scenic
     * 
     */
    @XmlEnumValue("scenic")
    SCENIC("scenic"),

    /**
     * Link is part of a built up area. Note that this flag will only be return when specifying generation 2 or later (see "gen" parameter).
     * 
     */
    @XmlEnumValue("builtUpArea")
    BUILT_UP_AREA("builtUpArea");
    private final String value;

    RouteLinkFlagType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouteLinkFlagType fromValue(String v) {
        for (RouteLinkFlagType c: RouteLinkFlagType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
