//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 * 				Note containing additional information about source data supplier.
 * 			
 * 
 * <p>Java class for SourceSupplierNoteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SourceSupplierNoteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Type" type="{http://www.navteq.com/lbsp/Routing-Common/4}SourceSupplierNoteTypeType"/>
 *         &lt;element name="Text" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Href" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="HrefText" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SourceSupplierNoteType", propOrder = {
    "type",
    "text",
    "href",
    "hrefText"
})
public class SourceSupplierNoteType {

    @XmlElement(name = "Type", required = true)
    protected SourceSupplierNoteTypeType type;
    @XmlElement(name = "Text", required = true)
    protected String text;
    @XmlElement(name = "Href")
    protected String href;
    @XmlElement(name = "HrefText")
    protected String hrefText;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link SourceSupplierNoteTypeType }
     *     
     */
    public SourceSupplierNoteTypeType getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link SourceSupplierNoteTypeType }
     *     
     */
    public void setType(SourceSupplierNoteTypeType value) {
        this.type = value;
    }

    /**
     * Gets the value of the text property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getText() {
        return text;
    }

    /**
     * Sets the value of the text property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setText(String value) {
        this.text = value;
    }

    /**
     * Gets the value of the href property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHref() {
        return href;
    }

    /**
     * Sets the value of the href property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHref(String value) {
        this.href = value;
    }

    /**
     * Gets the value of the hrefText property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHrefText() {
        return hrefText;
    }

    /**
     * Sets the value of the hrefText property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHrefText(String value) {
        this.hrefText = value;
    }

}
