//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:22 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcommon;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * This type is used to describe which restrictions apply on a link for trucks.
 * 
 * <p>Java class for TruckRestrictionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TruckRestrictionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TrailerForbidden" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="ForbiddenHazardousGoods" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}HazardousGoodTypeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PermittedGrossWeight" type="{http://www.navteq.com/lbsp/Common/4}WeightType" minOccurs="0"/>
 *         &lt;element name="LimitedWeight" type="{http://www.navteq.com/lbsp/Common/4}WeightType" minOccurs="0"/>
 *         &lt;element name="WeightPerAxle" type="{http://www.navteq.com/lbsp/Common/4}WeightType" minOccurs="0"/>
 *         &lt;element name="TrailerWeight" type="{http://www.navteq.com/lbsp/Common/4}WeightType" minOccurs="0"/>
 *         &lt;element name="Height" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Width" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="Length" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="TunnelCategory" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TruckRestrictionsType", propOrder = {
    "trailerForbidden",
    "forbiddenHazardousGoods",
    "permittedGrossWeight",
    "limitedWeight",
    "weightPerAxle",
    "trailerWeight",
    "height",
    "width",
    "length",
    "tunnelCategory"
})
public class TruckRestrictionsType {

    @XmlElement(name = "TrailerForbidden")
    protected Boolean trailerForbidden;
    @XmlList
    @XmlElement(name = "ForbiddenHazardousGoods")
    protected List<HazardousGoodTypeType> forbiddenHazardousGoods;
    @XmlElement(name = "PermittedGrossWeight")
    protected Double permittedGrossWeight;
    @XmlElement(name = "LimitedWeight")
    protected Double limitedWeight;
    @XmlElement(name = "WeightPerAxle")
    protected Double weightPerAxle;
    @XmlElement(name = "TrailerWeight")
    protected Double trailerWeight;
    @XmlElement(name = "Height")
    protected Double height;
    @XmlElement(name = "Width")
    protected Double width;
    @XmlElement(name = "Length")
    protected Double length;
    @XmlElement(name = "TunnelCategory")
    protected String tunnelCategory;

    /**
     * Gets the value of the trailerForbidden property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isTrailerForbidden() {
        return trailerForbidden;
    }

    /**
     * Sets the value of the trailerForbidden property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setTrailerForbidden(Boolean value) {
        this.trailerForbidden = value;
    }

    /**
     * Gets the value of the forbiddenHazardousGoods property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the forbiddenHazardousGoods property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getForbiddenHazardousGoods().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link HazardousGoodTypeType }
     * 
     * 
     */
    public List<HazardousGoodTypeType> getForbiddenHazardousGoods() {
        if (forbiddenHazardousGoods == null) {
            forbiddenHazardousGoods = new ArrayList<HazardousGoodTypeType>();
        }
        return this.forbiddenHazardousGoods;
    }

    /**
     * Gets the value of the permittedGrossWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPermittedGrossWeight() {
        return permittedGrossWeight;
    }

    /**
     * Sets the value of the permittedGrossWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPermittedGrossWeight(Double value) {
        this.permittedGrossWeight = value;
    }

    /**
     * Gets the value of the limitedWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLimitedWeight() {
        return limitedWeight;
    }

    /**
     * Sets the value of the limitedWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLimitedWeight(Double value) {
        this.limitedWeight = value;
    }

    /**
     * Gets the value of the weightPerAxle property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWeightPerAxle() {
        return weightPerAxle;
    }

    /**
     * Sets the value of the weightPerAxle property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWeightPerAxle(Double value) {
        this.weightPerAxle = value;
    }

    /**
     * Gets the value of the trailerWeight property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTrailerWeight() {
        return trailerWeight;
    }

    /**
     * Sets the value of the trailerWeight property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTrailerWeight(Double value) {
        this.trailerWeight = value;
    }

    /**
     * Gets the value of the height property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getHeight() {
        return height;
    }

    /**
     * Sets the value of the height property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setHeight(Double value) {
        this.height = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWidth(Double value) {
        this.width = value;
    }

    /**
     * Gets the value of the length property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getLength() {
        return length;
    }

    /**
     * Sets the value of the length property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setLength(Double value) {
        this.length = value;
    }

    /**
     * Gets the value of the tunnelCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTunnelCategory() {
        return tunnelCategory;
    }

    /**
     * Sets the value of the tunnelCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTunnelCategory(String value) {
        this.tunnelCategory = value;
    }

}
