//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculatematrix;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RouteNoteTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="RouteNoteTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="info"/>
 *     &lt;enumeration value="warning"/>
 *     &lt;enumeration value="restriction"/>
 *     &lt;enumeration value="violation"/>
 *     &lt;enumeration value="traffic"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "RouteNoteTypeType")
@XmlEnum
public enum RouteNoteTypeType {


    /**
     * Indicates an additional information for the maneuver or the segment leading to the maneuvr, like "border crossing", "segment includes tunnel/bridge/toll/unpaved/etc.".
     * 
     */
    @XmlEnumValue("info")
    INFO("info"),

    /**
     * Indicates a note with warning character, like "sharp curve ahead".
     * 
     */
    @XmlEnumValue("warning")
    WARNING("warning"),

    /**
     * Indicates a note providing additional information about e.g. time dependent restrictions on the segment ("road closed during winter").
     * 
     */
    @XmlEnumValue("restriction")
    RESTRICTION("restriction"),

    /**
     * Indicates a note providing additional information about violated routing options, e.g. route contains tollroads even though it has been requested to avoid tollroads.
     * 
     */
    @XmlEnumValue("violation")
    VIOLATION("violation"),

    /**
     * Indicates a note providing additional information on traffic.
     * 
     */
    @XmlEnumValue("traffic")
    TRAFFIC("traffic");
    private final String value;

    RouteNoteTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RouteNoteTypeType fromValue(String v) {
        for (RouteNoteTypeType c: RouteNoteTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
