//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculatematrix;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * In many use cases, not all objects and attributes in the route's object model are required at once. The enumeration type <b>RouteRepresentationMode</b> has been introduced to conveniently define which part of the route shall be returned by services for standard use cases. Any custom route representation definition besides these predefined modes is possible by using the detailed AttributeType switches (see <b>RouteAttribute</b>, <b>RouteLegAttribute</b>, <b>RouteAttribute</b>, <b>ManeuverAttribute</b> and <b>RouteLinkAttribute</b>).
 * 
 * <p>Java class for RouteRepresentationOptionsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteRepresentationOptionsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Language" type="{http://www.navteq.com/lbsp/Common/4}LanguageCodeParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="RepresentationMode" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteRepresentationModeType" minOccurs="0"/>
 *         &lt;element name="RouteAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}RouteAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LegAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}RouteLegAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="ManeuverAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}ManeuverAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="LinkAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}RouteLinkAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="CorridorDepth" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="CorridorOptions" type="{http://www.navteq.com/lbsp/Routing-Common/4}CorridorRepresentationOptionsType" minOccurs="0"/>
 *         &lt;element name="ViewBounds" type="{http://www.navteq.com/lbsp/Common/4}GeoBoundingBoxType" minOccurs="0"/>
 *         &lt;element name="ViewResolution" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="SnapResolution" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="InstructionFormat" type="{http://www.navteq.com/lbsp/Routing-Common/4}InstructionFormatType" minOccurs="0"/>
 *         &lt;element name="LineAttributes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportLineAttributeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteRepresentationOptionsType", propOrder = {
    "language",
    "representationMode",
    "routeAttributes",
    "legAttributes",
    "maneuverAttributes",
    "linkAttributes",
    "corridorDepth",
    "corridorOptions",
    "viewBounds",
    "viewResolution",
    "snapResolution",
    "instructionFormat",
    "lineAttributes"
})
public class RouteRepresentationOptionsType {

    @XmlElement(name = "Language")
    protected List<String> language;
    @XmlElement(name = "RepresentationMode")
    protected RouteRepresentationModeType representationMode;
    @XmlList
    @XmlElement(name = "RouteAttributes")
    protected List<RouteAttributeType> routeAttributes;
    @XmlList
    @XmlElement(name = "LegAttributes")
    protected List<RouteLegAttributeType> legAttributes;
    @XmlList
    @XmlElement(name = "ManeuverAttributes")
    protected List<ManeuverAttributeType> maneuverAttributes;
    @XmlList
    @XmlElement(name = "LinkAttributes")
    protected List<RouteLinkAttributeType> linkAttributes;
    @XmlElement(name = "CorridorDepth")
    protected Integer corridorDepth;
    @XmlElement(name = "CorridorOptions")
    protected CorridorRepresentationOptionsType corridorOptions;
    @XmlElement(name = "ViewBounds")
    protected GeoBoundingBoxType viewBounds;
    @XmlElement(name = "ViewResolution")
    protected Integer viewResolution;
    @XmlElement(name = "SnapResolution")
    protected Integer snapResolution;
    @XmlElement(name = "InstructionFormat")
    protected InstructionFormatType instructionFormat;
    @XmlList
    @XmlElement(name = "LineAttributes")
    protected List<PublicTransportLineAttributeType> lineAttributes;

    /**
     * Gets the value of the language property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the language property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLanguage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getLanguage() {
        if (language == null) {
            language = new ArrayList<String>();
        }
        return this.language;
    }

    /**
     * Gets the value of the representationMode property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRepresentationModeType }
     *     
     */
    public RouteRepresentationModeType getRepresentationMode() {
        return representationMode;
    }

    /**
     * Sets the value of the representationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRepresentationModeType }
     *     
     */
    public void setRepresentationMode(RouteRepresentationModeType value) {
        this.representationMode = value;
    }

    /**
     * Gets the value of the routeAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the routeAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRouteAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteAttributeType }
     * 
     * 
     */
    public List<RouteAttributeType> getRouteAttributes() {
        if (routeAttributes == null) {
            routeAttributes = new ArrayList<RouteAttributeType>();
        }
        return this.routeAttributes;
    }

    /**
     * Gets the value of the legAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the legAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLegAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteLegAttributeType }
     * 
     * 
     */
    public List<RouteLegAttributeType> getLegAttributes() {
        if (legAttributes == null) {
            legAttributes = new ArrayList<RouteLegAttributeType>();
        }
        return this.legAttributes;
    }

    /**
     * Gets the value of the maneuverAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the maneuverAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getManeuverAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ManeuverAttributeType }
     * 
     * 
     */
    public List<ManeuverAttributeType> getManeuverAttributes() {
        if (maneuverAttributes == null) {
            maneuverAttributes = new ArrayList<ManeuverAttributeType>();
        }
        return this.maneuverAttributes;
    }

    /**
     * Gets the value of the linkAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the linkAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLinkAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RouteLinkAttributeType }
     * 
     * 
     */
    public List<RouteLinkAttributeType> getLinkAttributes() {
        if (linkAttributes == null) {
            linkAttributes = new ArrayList<RouteLinkAttributeType>();
        }
        return this.linkAttributes;
    }

    /**
     * Gets the value of the corridorDepth property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getCorridorDepth() {
        return corridorDepth;
    }

    /**
     * Sets the value of the corridorDepth property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setCorridorDepth(Integer value) {
        this.corridorDepth = value;
    }

    /**
     * Gets the value of the corridorOptions property.
     * 
     * @return
     *     possible object is
     *     {@link CorridorRepresentationOptionsType }
     *     
     */
    public CorridorRepresentationOptionsType getCorridorOptions() {
        return corridorOptions;
    }

    /**
     * Sets the value of the corridorOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link CorridorRepresentationOptionsType }
     *     
     */
    public void setCorridorOptions(CorridorRepresentationOptionsType value) {
        this.corridorOptions = value;
    }

    /**
     * Gets the value of the viewBounds property.
     * 
     * @return
     *     possible object is
     *     {@link GeoBoundingBoxType }
     *     
     */
    public GeoBoundingBoxType getViewBounds() {
        return viewBounds;
    }

    /**
     * Sets the value of the viewBounds property.
     * 
     * @param value
     *     allowed object is
     *     {@link GeoBoundingBoxType }
     *     
     */
    public void setViewBounds(GeoBoundingBoxType value) {
        this.viewBounds = value;
    }

    /**
     * Gets the value of the viewResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getViewResolution() {
        return viewResolution;
    }

    /**
     * Sets the value of the viewResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setViewResolution(Integer value) {
        this.viewResolution = value;
    }

    /**
     * Gets the value of the snapResolution property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getSnapResolution() {
        return snapResolution;
    }

    /**
     * Sets the value of the snapResolution property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setSnapResolution(Integer value) {
        this.snapResolution = value;
    }

    /**
     * Gets the value of the instructionFormat property.
     * 
     * @return
     *     possible object is
     *     {@link InstructionFormatType }
     *     
     */
    public InstructionFormatType getInstructionFormat() {
        return instructionFormat;
    }

    /**
     * Sets the value of the instructionFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InstructionFormatType }
     *     
     */
    public void setInstructionFormat(InstructionFormatType value) {
        this.instructionFormat = value;
    }

    /**
     * Gets the value of the lineAttributes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the lineAttributes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLineAttributes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportLineAttributeType }
     * 
     * 
     */
    public List<PublicTransportLineAttributeType> getLineAttributes() {
        if (lineAttributes == null) {
            lineAttributes = new ArrayList<PublicTransportLineAttributeType>();
        }
        return this.lineAttributes;
    }

}
