//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:02 PM WET 
//


package com.trackit.presentation.view.map.provider.here.routes.routingcalculatematrix;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Each entry in the matrix provides one route starting from one of the start points and targeting at one of the destinations.
 * 
 * <p>Java class for RouteMatrixEntryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RouteMatrixEntryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="DestinationIndex" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;choice>
 *           &lt;choice>
 *             &lt;element name="Route" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteType"/>
 *             &lt;element name="Summary" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteSummaryType"/>
 *           &lt;/choice>
 *           &lt;element name="Status" type="{http://www.navteq.com/lbsp/Routing-CalculateMatrix/1}RouteStatusType"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RouteMatrixEntryType", namespace = "http://www.navteq.com/lbsp/Routing-CalculateMatrix/1", propOrder = {
    "startIndex",
    "destinationIndex",
    "route",
    "summary",
    "status"
})
public class RouteMatrixEntryType {

    @XmlElement(name = "StartIndex")
    protected Integer startIndex;
    @XmlElement(name = "DestinationIndex")
    protected Integer destinationIndex;
    @XmlElement(name = "Route")
    protected RouteType route;
    @XmlElement(name = "Summary")
    protected RouteSummaryType summary;
    @XmlElement(name = "Status")
    protected RouteStatusType status;

    /**
     * Gets the value of the startIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getStartIndex() {
        return startIndex;
    }

    /**
     * Sets the value of the startIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setStartIndex(Integer value) {
        this.startIndex = value;
    }

    /**
     * Gets the value of the destinationIndex property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getDestinationIndex() {
        return destinationIndex;
    }

    /**
     * Sets the value of the destinationIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setDestinationIndex(Integer value) {
        this.destinationIndex = value;
    }

    /**
     * Gets the value of the route property.
     * 
     * @return
     *     possible object is
     *     {@link RouteType }
     *     
     */
    public RouteType getRoute() {
        return route;
    }

    /**
     * Sets the value of the route property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteType }
     *     
     */
    public void setRoute(RouteType value) {
        this.route = value;
    }

    /**
     * Gets the value of the summary property.
     * 
     * @return
     *     possible object is
     *     {@link RouteSummaryType }
     *     
     */
    public RouteSummaryType getSummary() {
        return summary;
    }

    /**
     * Sets the value of the summary property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteSummaryType }
     *     
     */
    public void setSummary(RouteSummaryType value) {
        this.summary = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link RouteStatusType }
     *     
     */
    public RouteStatusType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteStatusType }
     *     
     */
    public void setStatus(RouteStatusType value) {
        this.status = value;
    }

}
