//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:12:49 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingversion;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingversion package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Version_QNAME = new QName("http://www.navteq.com/lbsp/Routing-Version/1", "Version");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingversion
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link VersionType }
     * 
     */
    public VersionType createVersionType() {
        return new VersionType();
    }

    /**
     * Create an instance of {@link VersionResponseMetaInfoType }
     * 
     */
    public VersionResponseMetaInfoType createVersionResponseMetaInfoType() {
        return new VersionResponseMetaInfoType();
    }

    /**
     * Create an instance of {@link VersionResponseType }
     * 
     */
    public VersionResponseType createVersionResponseType() {
        return new VersionResponseType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link VersionType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.navteq.com/lbsp/Routing-Version/1", name = "Version")
    public JAXBElement<VersionType> createVersion(VersionType value) {
        return new JAXBElement<VersionType>(_Version_QNAME, VersionType.class, null, value);
    }

}
