//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for CalculateRouteType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculateRouteType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Request" type="{http://www.navteq.com/lbsp/Routing-CalculateRoute/4}CalculateRouteRequestType" minOccurs="0"/>
 *         &lt;element name="Response" type="{http://www.navteq.com/lbsp/Routing-CalculateRoute/4}CalculateRouteResponseType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculateRoute", namespace = "http://www.navteq.com/lbsp/Routing-CalculateRoute/4", propOrder = {
    "request",
    "response"
})
public class CalculateRouteType {

    @XmlElement(name = "Request")
    protected CalculateRouteRequestType request;
    @XmlElement(name = "Response")
    protected CalculateRouteResponseType response;

    /**
     * Gets the value of the request property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateRouteRequestType }
     *     
     */
    public CalculateRouteRequestType getRequest() {
        return request;
    }

    /**
     * Sets the value of the request property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateRouteRequestType }
     *     
     */
    public void setRequest(CalculateRouteRequestType value) {
        this.request = value;
    }

    /**
     * Gets the value of the response property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateRouteResponseType }
     *     
     */
    public CalculateRouteResponseType getResponse() {
        return response;
    }

    /**
     * Sets the value of the response property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateRouteResponseType }
     *     
     */
    public void setResponse(CalculateRouteResponseType value) {
        this.response = value;
    }

}
