//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <b>CalculateRouteRequest</b> is the data structure for calling the CalculateRoute service.
 * 
 * <p>Java class for CalculateRouteRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CalculateRouteRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MetaInfo" type="{http://www.navteq.com/lbsp/Routing-CalculateRoute/4}CalculateRouteRequestMetaInfoType" minOccurs="0"/>
 *         &lt;element name="RepresentationOptions" type="{http://www.navteq.com/lbsp/Routing-Common/4}RouteRepresentationOptionsType" minOccurs="0"/>
 *         &lt;element name="Waypoint" type="{http://www.navteq.com/lbsp/Routing-Common/4}WaypointParameterType" maxOccurs="unbounded" minOccurs="2"/>
 *         &lt;element name="AvoidArea" type="{http://www.navteq.com/lbsp/Common/4}GeoBoundingBoxType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AvoidLinks" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Common/4}LinkIdType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Departure" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Arrival" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *         &lt;element name="Alternatives" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="Mode" type="{http://www.navteq.com/lbsp/Routing-Common/4}RoutingModeType" maxOccurs="unbounded"/>
 *         &lt;element name="PublicTransportProfile" type="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportProfileType" minOccurs="0"/>
 *         &lt;element name="TruckProfile" type="{http://www.navteq.com/lbsp/Routing-Common/4}TruckProfileType" minOccurs="0"/>
 *         &lt;element name="AdditionalData" type="{http://www.navteq.com/lbsp/Common/4}KeyValuePairType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="NavigationMode" type="{http://www.navteq.com/lbsp/Routing-Common/4}NavigationModeType" minOccurs="0"/>
 *         &lt;element name="GeneralizationTolerances" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.w3.org/2001/XMLSchema}double" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="MetricSystem" type="{http://www.navteq.com/lbsp/Common/4}MetricSystemType" minOccurs="0"/>
 *         &lt;element name="DistanceBeforeFirstTurn" type="{http://www.navteq.com/lbsp/Common/4}DistanceType" minOccurs="0"/>
 *         &lt;element name="Vehicle" type="{http://www.navteq.com/lbsp/Routing-Common/4}VehicleType" minOccurs="0"/>
 *         &lt;element name="Gen" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CalculateRouteRequestType", namespace = "http://www.navteq.com/lbsp/Routing-CalculateRoute/4", propOrder = {
    "metaInfo",
    "representationOptions",
    "waypoint",
    "avoidArea",
    "avoidLinks",
    "departure",
    "arrival",
    "alternatives",
    "mode",
    "publicTransportProfile",
    "truckProfile",
    "additionalData",
    "navigationMode",
    "generalizationTolerances",
    "metricSystem",
    "distanceBeforeFirstTurn",
    "vehicle",
    "gen"
})
public class CalculateRouteRequestType {

    @XmlElement(name = "MetaInfo")
    protected CalculateRouteRequestMetaInfoType metaInfo;
    @XmlElement(name = "RepresentationOptions")
    protected RouteRepresentationOptionsType representationOptions;
    @XmlElement(name = "Waypoint", required = true)
    protected List<WaypointParameterType> waypoint;
    @XmlElement(name = "AvoidArea")
    protected List<GeoBoundingBoxType> avoidArea;
    @XmlList
    @XmlElement(name = "AvoidLinks")
    protected List<String> avoidLinks;
    @XmlElement(name = "Departure")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar departure;
    @XmlElement(name = "Arrival")
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar arrival;
    @XmlElement(name = "Alternatives")
    protected Integer alternatives;
    @XmlElement(name = "Mode", required = true)
    protected List<RoutingModeType> mode;
    @XmlElement(name = "PublicTransportProfile")
    protected PublicTransportProfileType publicTransportProfile;
    @XmlElement(name = "TruckProfile")
    protected TruckProfileType truckProfile;
    @XmlElement(name = "AdditionalData")
    protected List<KeyValuePairType> additionalData;
    @XmlElement(name = "NavigationMode")
    protected NavigationModeType navigationMode;
    @XmlList
    @XmlElement(name = "GeneralizationTolerances", type = Double.class)
    protected List<Double> generalizationTolerances;
    @XmlElement(name = "MetricSystem")
    protected MetricSystemType metricSystem;
    @XmlElement(name = "DistanceBeforeFirstTurn")
    protected Double distanceBeforeFirstTurn;
    @XmlElement(name = "Vehicle")
    protected VehicleType vehicle;
    @XmlElement(name = "Gen")
    protected Integer gen;

    /**
     * Gets the value of the metaInfo property.
     * 
     * @return
     *     possible object is
     *     {@link CalculateRouteRequestMetaInfoType }
     *     
     */
    public CalculateRouteRequestMetaInfoType getMetaInfo() {
        return metaInfo;
    }

    /**
     * Sets the value of the metaInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link CalculateRouteRequestMetaInfoType }
     *     
     */
    public void setMetaInfo(CalculateRouteRequestMetaInfoType value) {
        this.metaInfo = value;
    }

    /**
     * Gets the value of the representationOptions property.
     * 
     * @return
     *     possible object is
     *     {@link RouteRepresentationOptionsType }
     *     
     */
    public RouteRepresentationOptionsType getRepresentationOptions() {
        return representationOptions;
    }

    /**
     * Sets the value of the representationOptions property.
     * 
     * @param value
     *     allowed object is
     *     {@link RouteRepresentationOptionsType }
     *     
     */
    public void setRepresentationOptions(RouteRepresentationOptionsType value) {
        this.representationOptions = value;
    }

    /**
     * Gets the value of the waypoint property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the waypoint property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getWaypoint().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link WaypointParameterType }
     * 
     * 
     */
    public List<WaypointParameterType> getWaypoint() {
        if (waypoint == null) {
            waypoint = new ArrayList<WaypointParameterType>();
        }
        return this.waypoint;
    }

    /**
     * Gets the value of the avoidArea property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidArea property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidArea().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GeoBoundingBoxType }
     * 
     * 
     */
    public List<GeoBoundingBoxType> getAvoidArea() {
        if (avoidArea == null) {
            avoidArea = new ArrayList<GeoBoundingBoxType>();
        }
        return this.avoidArea;
    }

    /**
     * Gets the value of the avoidLinks property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidLinks property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidLinks().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getAvoidLinks() {
        if (avoidLinks == null) {
            avoidLinks = new ArrayList<String>();
        }
        return this.avoidLinks;
    }

    /**
     * Gets the value of the departure property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeparture() {
        return departure;
    }

    /**
     * Sets the value of the departure property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeparture(XMLGregorianCalendar value) {
        this.departure = value;
    }

    /**
     * Gets the value of the arrival property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getArrival() {
        return arrival;
    }

    /**
     * Sets the value of the arrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setArrival(XMLGregorianCalendar value) {
        this.arrival = value;
    }

    /**
     * Gets the value of the alternatives property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAlternatives() {
        return alternatives;
    }

    /**
     * Sets the value of the alternatives property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAlternatives(Integer value) {
        this.alternatives = value;
    }

    /**
     * Gets the value of the mode property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mode property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMode().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link RoutingModeType }
     * 
     * 
     */
    public List<RoutingModeType> getMode() {
        if (mode == null) {
            mode = new ArrayList<RoutingModeType>();
        }
        return this.mode;
    }

    /**
     * Gets the value of the publicTransportProfile property.
     * 
     * @return
     *     possible object is
     *     {@link PublicTransportProfileType }
     *     
     */
    public PublicTransportProfileType getPublicTransportProfile() {
        return publicTransportProfile;
    }

    /**
     * Sets the value of the publicTransportProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicTransportProfileType }
     *     
     */
    public void setPublicTransportProfile(PublicTransportProfileType value) {
        this.publicTransportProfile = value;
    }

    /**
     * Gets the value of the truckProfile property.
     * 
     * @return
     *     possible object is
     *     {@link TruckProfileType }
     *     
     */
    public TruckProfileType getTruckProfile() {
        return truckProfile;
    }

    /**
     * Sets the value of the truckProfile property.
     * 
     * @param value
     *     allowed object is
     *     {@link TruckProfileType }
     *     
     */
    public void setTruckProfile(TruckProfileType value) {
        this.truckProfile = value;
    }

    /**
     * Gets the value of the additionalData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the additionalData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAdditionalData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KeyValuePairType }
     * 
     * 
     */
    public List<KeyValuePairType> getAdditionalData() {
        if (additionalData == null) {
            additionalData = new ArrayList<KeyValuePairType>();
        }
        return this.additionalData;
    }

    /**
     * Gets the value of the navigationMode property.
     * 
     * @return
     *     possible object is
     *     {@link NavigationModeType }
     *     
     */
    public NavigationModeType getNavigationMode() {
        return navigationMode;
    }

    /**
     * Sets the value of the navigationMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link NavigationModeType }
     *     
     */
    public void setNavigationMode(NavigationModeType value) {
        this.navigationMode = value;
    }

    /**
     * Gets the value of the generalizationTolerances property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the generalizationTolerances property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGeneralizationTolerances().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Double }
     * 
     * 
     */
    public List<Double> getGeneralizationTolerances() {
        if (generalizationTolerances == null) {
            generalizationTolerances = new ArrayList<Double>();
        }
        return this.generalizationTolerances;
    }

    /**
     * Gets the value of the metricSystem property.
     * 
     * @return
     *     possible object is
     *     {@link MetricSystemType }
     *     
     */
    public MetricSystemType getMetricSystem() {
        return metricSystem;
    }

    /**
     * Sets the value of the metricSystem property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetricSystemType }
     *     
     */
    public void setMetricSystem(MetricSystemType value) {
        this.metricSystem = value;
    }

    /**
     * Gets the value of the distanceBeforeFirstTurn property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getDistanceBeforeFirstTurn() {
        return distanceBeforeFirstTurn;
    }

    /**
     * Sets the value of the distanceBeforeFirstTurn property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setDistanceBeforeFirstTurn(Double value) {
        this.distanceBeforeFirstTurn = value;
    }

    /**
     * Gets the value of the vehicle property.
     * 
     * @return
     *     possible object is
     *     {@link VehicleType }
     *     
     */
    public VehicleType getVehicle() {
        return vehicle;
    }

    /**
     * Sets the value of the vehicle property.
     * 
     * @param value
     *     allowed object is
     *     {@link VehicleType }
     *     
     */
    public void setVehicle(VehicleType value) {
        this.vehicle = value;
    }

    /**
     * Gets the value of the gen property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getGen() {
        return gen;
    }

    /**
     * Sets the value of the gen property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setGen(Integer value) {
        this.gen = value;
    }

}
