//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for IncidentTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="IncidentTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="accident"/>
 *     &lt;enumeration value="congestion"/>
 *     &lt;enumeration value="disabledVehicle"/>
 *     &lt;enumeration value="roadHazard"/>
 *     &lt;enumeration value="construction"/>
 *     &lt;enumeration value="plannedEvent"/>
 *     &lt;enumeration value="massTransit"/>
 *     &lt;enumeration value="otherNews"/>
 *     &lt;enumeration value="weather"/>
 *     &lt;enumeration value="alert"/>
 *     &lt;enumeration value="miscellaneous"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "IncidentTypeType")
@XmlEnum
public enum IncidentTypeType {

    @XmlEnumValue("accident")
    ACCIDENT("accident"),
    @XmlEnumValue("congestion")
    CONGESTION("congestion"),
    @XmlEnumValue("disabledVehicle")
    DISABLED_VEHICLE("disabledVehicle"),
    @XmlEnumValue("roadHazard")
    ROAD_HAZARD("roadHazard"),
    @XmlEnumValue("construction")
    CONSTRUCTION("construction"),
    @XmlEnumValue("plannedEvent")
    PLANNED_EVENT("plannedEvent"),
    @XmlEnumValue("massTransit")
    MASS_TRANSIT("massTransit"),
    @XmlEnumValue("otherNews")
    OTHER_NEWS("otherNews"),
    @XmlEnumValue("weather")
    WEATHER("weather"),
    @XmlEnumValue("alert")
    ALERT("alert"),
    @XmlEnumValue("miscellaneous")
    MISCELLANEOUS("miscellaneous");
    private final String value;

    IncidentTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static IncidentTypeType fromValue(String v) {
        for (IncidentTypeType c: IncidentTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
