//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.navteq.com/lbsp/Routing-Common/4")
package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;
