//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlList;
import javax.xml.bind.annotation.XmlType;


/**
 * Defines settings relevant for public transport routing.
 * <i>Note: not yet supported</i>
 * 
 * <p>Java class for PublicTransportProfileType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicTransportProfileType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MaxNumberOfChanges" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="MinDurationForChange" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="AvoidTransportTypes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportTypeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="PreferredTransportTypes" minOccurs="0">
 *           &lt;simpleType>
 *             &lt;list itemType="{http://www.navteq.com/lbsp/Routing-Common/4}PublicTransportTypeType" />
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="SystemId" type="{http://www.navteq.com/lbsp/Common/4}TransitSystemIdType" minOccurs="0"/>
 *         &lt;element name="Walkspeed" type="{http://www.navteq.com/lbsp/Common/4}SpeedType" minOccurs="0"/>
 *         &lt;element name="WalkTimeMultiplier" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/>
 *         &lt;element name="MaxWalkDistance" type="{http://www.navteq.com/lbsp/Common/4}DistanceType" minOccurs="0"/>
 *         &lt;element name="BeforeDepart" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AfterDepart" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="BeforeArrival" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="AfterArrival" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="TimeBefore" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="TimeAfter" type="{http://www.navteq.com/lbsp/Common/4}DurationType" minOccurs="0"/>
 *         &lt;element name="CombineChange" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="CollapseDepartArriveManeuvers" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicTransportProfileType", propOrder = {
    "maxNumberOfChanges",
    "minDurationForChange",
    "avoidTransportTypes",
    "preferredTransportTypes",
    "systemId",
    "walkspeed",
    "walkTimeMultiplier",
    "maxWalkDistance",
    "beforeDepart",
    "afterDepart",
    "beforeArrival",
    "afterArrival",
    "timeBefore",
    "timeAfter",
    "combineChange",
    "collapseDepartArriveManeuvers"
})
public class PublicTransportProfileType {

    @XmlElement(name = "MaxNumberOfChanges")
    protected Integer maxNumberOfChanges;
    @XmlElement(name = "MinDurationForChange")
    protected Double minDurationForChange;
    @XmlList
    @XmlElement(name = "AvoidTransportTypes")
    protected List<PublicTransportTypeType> avoidTransportTypes;
    @XmlList
    @XmlElement(name = "PreferredTransportTypes")
    protected List<PublicTransportTypeType> preferredTransportTypes;
    @XmlElement(name = "SystemId")
    protected String systemId;
    @XmlElement(name = "Walkspeed")
    protected Double walkspeed;
    @XmlElement(name = "WalkTimeMultiplier")
    protected Double walkTimeMultiplier;
    @XmlElement(name = "MaxWalkDistance")
    protected Double maxWalkDistance;
    @XmlElement(name = "BeforeDepart")
    protected Integer beforeDepart;
    @XmlElement(name = "AfterDepart")
    protected Integer afterDepart;
    @XmlElement(name = "BeforeArrival")
    protected Integer beforeArrival;
    @XmlElement(name = "AfterArrival")
    protected Integer afterArrival;
    @XmlElement(name = "TimeBefore")
    protected Double timeBefore;
    @XmlElement(name = "TimeAfter")
    protected Double timeAfter;
    @XmlElement(name = "CombineChange")
    protected Boolean combineChange;
    @XmlElement(name = "CollapseDepartArriveManeuvers")
    protected Boolean collapseDepartArriveManeuvers;

    /**
     * Gets the value of the maxNumberOfChanges property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxNumberOfChanges() {
        return maxNumberOfChanges;
    }

    /**
     * Sets the value of the maxNumberOfChanges property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxNumberOfChanges(Integer value) {
        this.maxNumberOfChanges = value;
    }

    /**
     * Gets the value of the minDurationForChange property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMinDurationForChange() {
        return minDurationForChange;
    }

    /**
     * Sets the value of the minDurationForChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMinDurationForChange(Double value) {
        this.minDurationForChange = value;
    }

    /**
     * Gets the value of the avoidTransportTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the avoidTransportTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAvoidTransportTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportTypeType }
     * 
     * 
     */
    public List<PublicTransportTypeType> getAvoidTransportTypes() {
        if (avoidTransportTypes == null) {
            avoidTransportTypes = new ArrayList<PublicTransportTypeType>();
        }
        return this.avoidTransportTypes;
    }

    /**
     * Gets the value of the preferredTransportTypes property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the preferredTransportTypes property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPreferredTransportTypes().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicTransportTypeType }
     * 
     * 
     */
    public List<PublicTransportTypeType> getPreferredTransportTypes() {
        if (preferredTransportTypes == null) {
            preferredTransportTypes = new ArrayList<PublicTransportTypeType>();
        }
        return this.preferredTransportTypes;
    }

    /**
     * Gets the value of the systemId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSystemId() {
        return systemId;
    }

    /**
     * Sets the value of the systemId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSystemId(String value) {
        this.systemId = value;
    }

    /**
     * Gets the value of the walkspeed property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWalkspeed() {
        return walkspeed;
    }

    /**
     * Sets the value of the walkspeed property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWalkspeed(Double value) {
        this.walkspeed = value;
    }

    /**
     * Gets the value of the walkTimeMultiplier property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getWalkTimeMultiplier() {
        return walkTimeMultiplier;
    }

    /**
     * Sets the value of the walkTimeMultiplier property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setWalkTimeMultiplier(Double value) {
        this.walkTimeMultiplier = value;
    }

    /**
     * Gets the value of the maxWalkDistance property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getMaxWalkDistance() {
        return maxWalkDistance;
    }

    /**
     * Sets the value of the maxWalkDistance property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setMaxWalkDistance(Double value) {
        this.maxWalkDistance = value;
    }

    /**
     * Gets the value of the beforeDepart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBeforeDepart() {
        return beforeDepart;
    }

    /**
     * Sets the value of the beforeDepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBeforeDepart(Integer value) {
        this.beforeDepart = value;
    }

    /**
     * Gets the value of the afterDepart property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAfterDepart() {
        return afterDepart;
    }

    /**
     * Sets the value of the afterDepart property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAfterDepart(Integer value) {
        this.afterDepart = value;
    }

    /**
     * Gets the value of the beforeArrival property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getBeforeArrival() {
        return beforeArrival;
    }

    /**
     * Sets the value of the beforeArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setBeforeArrival(Integer value) {
        this.beforeArrival = value;
    }

    /**
     * Gets the value of the afterArrival property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getAfterArrival() {
        return afterArrival;
    }

    /**
     * Sets the value of the afterArrival property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setAfterArrival(Integer value) {
        this.afterArrival = value;
    }

    /**
     * Gets the value of the timeBefore property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTimeBefore() {
        return timeBefore;
    }

    /**
     * Sets the value of the timeBefore property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTimeBefore(Double value) {
        this.timeBefore = value;
    }

    /**
     * Gets the value of the timeAfter property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getTimeAfter() {
        return timeAfter;
    }

    /**
     * Sets the value of the timeAfter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setTimeAfter(Double value) {
        this.timeAfter = value;
    }

    /**
     * Gets the value of the combineChange property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCombineChange() {
        return combineChange;
    }

    /**
     * Sets the value of the combineChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCombineChange(Boolean value) {
        this.combineChange = value;
    }

    /**
     * Gets the value of the collapseDepartArriveManeuvers property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isCollapseDepartArriveManeuvers() {
        return collapseDepartArriveManeuvers;
    }

    /**
     * Sets the value of the collapseDepartArriveManeuvers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setCollapseDepartArriveManeuvers(Boolean value) {
        this.collapseDepartArriveManeuvers = value;
    }

}
