//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ResourceTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ResourceTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="junctionView"/>
 *     &lt;enumeration value="signAsReal"/>
 *     &lt;enumeration value="directionArrow"/>
 *     &lt;enumeration value="advertising"/>
 *     &lt;enumeration value="vendorIcon"/>
 *     &lt;enumeration value="vendorLogo"/>
 *     &lt;enumeration value="routeTemplate"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ResourceTypeType")
@XmlEnum
public enum ResourceTypeType {


    /**
     * Identifier for the bitmap representing the Junction View.
     * 
     */
    @XmlEnumValue("junctionView")
    JUNCTION_VIEW("junctionView"),

    /**
     * Identifier for the bitmap representing the sign-as-real information.
     * 
     */
    @XmlEnumValue("signAsReal")
    SIGN_AS_REAL("signAsReal"),

    /**
     * Identifier for the bitmap representing the direction arrow at a junction which will be displayed on top of the junction view.
     * 
     */
    @XmlEnumValue("directionArrow")
    DIRECTION_ARROW("directionArrow"),

    /**
     * Identifier for the bitmap representing any kind of advertisement.
     * 
     */
    @XmlEnumValue("advertising")
    ADVERTISING("advertising"),

    /**
     * Identifier for the bitmap representing the vendor icon e.g. of a public transport system.
     * 
     */
    @XmlEnumValue("vendorIcon")
    VENDOR_ICON("vendorIcon"),

    /**
     * Identifier for the bitmap representing the vendor logo e.g. of a public transport system.
     * 
     */
    @XmlEnumValue("vendorLogo")
    VENDOR_LOGO("vendorLogo"),

    /**
     * Identifier for the svg resource representing a template for displaying routes (e.g. highway signs). Clients will have to include the route number in the graphic to display a concrete route sign.
     * 
     */
    @XmlEnumValue("routeTemplate")
    ROUTE_TEMPLATE("routeTemplate");
    private final String value;

    ResourceTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ResourceTypeType fromValue(String v) {
        for (ResourceTypeType c: ResourceTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
