//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.03.29 at 05:11:32 PM WET 
//


package com.henriquemalheiro.trackit.presentation.view.map.provider.heremaps.routes.routingcalculateroute;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WaypointParameterTypeType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WaypointParameterTypeType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="stopOver"/>
 *     &lt;enumeration value="passThrough"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "WaypointParameterTypeType")
@XmlEnum
public enum WaypointParameterTypeType {


    /**
     * Identifies a stopover waypoint. At a stopover 180 degree turns are allowed to continue on the route.
     * 
     */
    @XmlEnumValue("stopOver")
    STOP_OVER("stopOver"),

    /**
     * Identifies a pass-through waypoint. At a pass-through waypoint the route is not expected to support a break therefore no 180 degree turns are allowed. Waypoints defined through a drag-n-drop action should be marked as pass-through.
     * 
     */
    @XmlEnumValue("passThrough")
    PASS_THROUGH("passThrough");
    private final String value;

    WaypointParameterTypeType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WaypointParameterTypeType fromValue(String v) {
        for (WaypointParameterTypeType c: WaypointParameterTypeType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
